DevToys-app/DevToys

- src/dev/impl/DevToys/Core/Logger.cs
The Open Logs button doesn't do anything if there are no logs.
Issue Number: #9
When there's no logs, create an empty log file and open it.
> Fixed #9 : logs won't open if there's no log at all.

- THIRD-PARTY-NOTICES.md
- src/Directory.Build.props
- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/en/Settings.resw
- src/dev/impl/DevToys/Strings/fr/Settings.resw
- src/dev/impl/DevToys/ViewModels/Tools/Settings/SettingsToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Settings/SettingsToolPage.xaml
> Fixed Settings page internationalization and improved version number display

- src/dev/impl/DevToys/UI/Controls/FormattedTextBlock/FormattedTextBlock.xaml.cs
Issue Number: #11 
- The application won't crash when the output field is empty
> added null check on empty document on copy button click

- src/dev/impl/DevToys/UI/Controls/ExpandableSettingControl.xaml
- src/dev/impl/DevToys/UI/Controls/ExpandableSettingControl.xaml.cs
- src/dev/impl/DevToys/UI/Controls/ExpandableSettingHeaderControl.xaml
- src/dev/impl/DevToys/Views/Tools/RegEx/RegExToolPage.xaml
Issue Number: #46 
Fixed this issue by using {ThemeResource} markup.
> Fixed a bug with dark theme

- src/dev/impl/DevToys/Strings/cs-CZ/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/cs-CZ/MainPage.resw
- src/dev/impl/DevToys/Strings/cs-CZ/UrlEncoderDecoder.resw
- Url E/D, Html E/D and Guid Generator are not translated.
- There are some strings in MainPage that are not translated.
- Translated the newly added tools - Url E/D, Html E/D, and Guid Generator.
- And also translated some new strings in the MainPage.
> Updated Czech translation [cs-CZ]

- src/dev/impl/DevToys/Strings/zh-CN/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-CN/Common.resw
- src/dev/impl/DevToys/Strings/zh-CN/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/zh-CN/HashGenerator.resw
- src/dev/impl/DevToys/Strings/zh-CN/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-CN/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/zh-CN/JsonYaml.resw
- src/dev/impl/DevToys/Strings/zh-CN/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/zh-CN/MainPage.resw
- src/dev/impl/DevToys/Strings/zh-CN/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/zh-CN/RegEx.resw
- src/dev/impl/DevToys/Strings/zh-CN/Settings.resw
- src/dev/impl/DevToys/Strings/zh-CN/StringUtilities.resw
- src/dev/impl/DevToys/Strings/zh-CN/TextDiff.resw
- src/dev/impl/DevToys/Strings/zh-CN/UrlEncoderDecoder.resw
There is no localization file for Simplified Chinese.
Added translation for Simplified Chinese.
> Added localization files for Simplified Chinese

- README.md
There's no documentation about how to install DevToys through WinGet.
Issue Number: #77
Added that documentation
> Added documentation about WinGet

- README.md
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/cs-CZ/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/en-US/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/fr-FR/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/pl-PL/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/ru-RU/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/zh-CN/GuidGenerator.resw
- src/dev/impl/DevToys/ViewModels/Tools/GuidGenerator/GuidGeneratorToolProvider.cs
- src/dev/impl/DevToys/ViewModels/Tools/GuidGenerator/GuidGeneratorToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/GuidGenerator/GuidGeneratorToolPage.xaml
GUID Generator only generate UUID version 4.
Issue Number: #89 
Added the support of UUID version 1.
> Added support of UUID version 1 in GUID Generator tool

- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs
- src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs
Copying from Code Editor or Custom Text Box sometimes fail for an unknown reason.
Issue Number: #96
Swallow the issue and log a faulty log.
> Fix 96 - Log Copy button failure

- src/dev/impl/DevToys/ViewModels/Tools/NumberBaseConverter/NumberBaseFormatter.cs
When building DevToys, I got some warning about possible null reference exception in NumberBaseFormatter.
Fixed them.
> Removed some possible NRE

- src/dev/impl/DevToys.MonacoEditor/CodeEditorControl/CodeEditorCore.cs
- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml
- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs
When Monaco Editor crashes for some reason, the app displays an error message.
Issue Number: #78
Monaco Editor will now try to reload up to 5 times and then show an error message if it keeps crashing.
> Try to reload Monaco Editor when it fails.

- src/dev/impl/DevToys/Core/ToolProviderFactory.cs
After doing a search in the Search Box, the order of tools items in the Grid View may change.
Fixed the bug by making the SortTools method optionally taking considering of match spans.
> Fixed a bug where tools orders in the grid view would change following a search.

- src/dev/impl/DevToys/UI/Extensions/HighlighterExtension.cs
- src/dev/impl/DevToys/ViewModels/Tools/Text/RegEx/RegExToolViewModel.cs
Highlighting color was yellow.
Issue Number: #32
> Changed the highlighting color so it uses the accent color.

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/cs-CZ/AllTools.resw
- src/dev/impl/DevToys/Strings/cs-CZ/SearchResult.resw
- src/dev/impl/DevToys/Strings/en-US/SearchResult.resw
- src/dev/impl/DevToys/Strings/fr-FR/AllTools.resw
- src/dev/impl/DevToys/Strings/fr-FR/SearchResult.resw
- src/dev/impl/DevToys/Strings/pl-PL/AllTools.resw
- src/dev/impl/DevToys/Strings/pl-PL/SearchResult.resw
- src/dev/impl/DevToys/Strings/ru-RU/AllTools.resw
- src/dev/impl/DevToys/Strings/ru-RU/SearchResult.resw
- src/dev/impl/DevToys/Strings/zh-CN/AllTools.resw
- src/dev/impl/DevToys/Strings/zh-CN/SearchResult.resw
- src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/GroupToolProviderBase.cs
- src/dev/impl/DevToys/ViewModels/Tools/SearchResult/SearchResultToolProvider.cs
When doing a search, there's no way to display a page showing all the search results or "no result found".
Added a page that shows search results.
> Show a page for search results

- src/dev/impl/DevToys/Core/UriActivationProtocolService.cs
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/cs-CZ/Common.resw
- src/dev/impl/DevToys/Strings/cs-CZ/MainPage.resw
- src/dev/impl/DevToys/Strings/en-US/MainPage.resw
- src/dev/impl/DevToys/Strings/fr-FR/Common.resw
- src/dev/impl/DevToys/Strings/fr-FR/MainPage.resw
- src/dev/impl/DevToys/Strings/pl-PL/Common.resw
- src/dev/impl/DevToys/Strings/pl-PL/MainPage.resw
- src/dev/impl/DevToys/Strings/ru-RU/Common.resw
- src/dev/impl/DevToys/Strings/ru-RU/MainPage.resw
- src/dev/impl/DevToys/Strings/zh-CN/Common.resw
- src/dev/impl/DevToys/Strings/zh-CN/MainPage.resw
- src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
User clicks on `Pin tool to start`, but nothing happens.
Issue Number: #120
It appears that icons are installed based on OS configuration. We now safely ignore non-installed files and pick up the best generated icons.
> Fixed an NRE when generating tile icons.

- src/dev/impl/DevToys/Strings/ru-RU/AllTools.resw
- src/dev/impl/DevToys/Strings/ru-RU/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ru-RU/Common.resw
- src/dev/impl/DevToys/Strings/ru-RU/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/ru-RU/HashGenerator.resw
- src/dev/impl/DevToys/Strings/ru-RU/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ru-RU/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/ru-RU/JsonYaml.resw
- src/dev/impl/DevToys/Strings/ru-RU/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/ru-RU/MainPage.resw
- src/dev/impl/DevToys/Strings/ru-RU/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/ru-RU/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/ru-RU/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/ru-RU/RegEx.resw
- src/dev/impl/DevToys/Strings/ru-RU/SearchResult.resw
- src/dev/impl/DevToys/Strings/ru-RU/Settings.resw
- src/dev/impl/DevToys/Strings/ru-RU/StringUtilities.resw
- src/dev/impl/DevToys/Strings/ru-RU/TextDiff.resw
- src/dev/impl/DevToys/Strings/ru-RU/ToolGroups.resw
- src/dev/impl/DevToys/Strings/ru-RU/UrlEncoderDecoder.resw
> Updated localization files for Russian language

- src/dev/impl/DevToys/ViewModels/Tools/ToolProviderBase.cs
> Fixed blurry SVG icons

- src/dev/impl/DevToys/Strings/zh-CN/AllTools.resw
- src/dev/impl/DevToys/Strings/zh-CN/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-CN/Common.resw
- src/dev/impl/DevToys/Strings/zh-CN/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/zh-CN/HashGenerator.resw
- src/dev/impl/DevToys/Strings/zh-CN/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-CN/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/zh-CN/JsonYaml.resw
- src/dev/impl/DevToys/Strings/zh-CN/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/zh-CN/MainPage.resw
- src/dev/impl/DevToys/Strings/zh-CN/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/zh-CN/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/zh-CN/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/zh-CN/RegEx.resw
- src/dev/impl/DevToys/Strings/zh-CN/SearchResult.resw
- src/dev/impl/DevToys/Strings/zh-CN/Settings.resw
- src/dev/impl/DevToys/Strings/zh-CN/StringUtilities.resw
- src/dev/impl/DevToys/Strings/zh-CN/TextDiff.resw
- src/dev/impl/DevToys/Strings/zh-CN/ToolGroups.resw
- src/dev/impl/DevToys/Strings/zh-CN/UrlEncoderDecoder.resw
-
-
-
Hope to reupdate simplified Chinese translation
希望能够再更新一下简体中文的翻译
> update simplified Chinese translation

- src/dev/impl/DevToys/Strings/pt-PT/AllTools.resw
- src/dev/impl/DevToys/Strings/pt-PT/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-PT/Common.resw
- src/dev/impl/DevToys/Strings/pt-PT/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/pt-PT/HashGenerator.resw
- src/dev/impl/DevToys/Strings/pt-PT/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-PT/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/pt-PT/JsonYaml.resw
- src/dev/impl/DevToys/Strings/pt-PT/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/pt-PT/MainPage.resw
- src/dev/impl/DevToys/Strings/pt-PT/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/pt-PT/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/pt-PT/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/pt-PT/RegEx.resw
- src/dev/impl/DevToys/Strings/pt-PT/SearchResult.resw
- src/dev/impl/DevToys/Strings/pt-PT/Settings.resw
- src/dev/impl/DevToys/Strings/pt-PT/StringUtilities.resw
- src/dev/impl/DevToys/Strings/pt-PT/TextDiff.resw
- src/dev/impl/DevToys/Strings/pt-PT/ToolGroups.resw
- src/dev/impl/DevToys/Strings/pt-PT/UrlEncoderDecoder.resw
- DevToys does not have Portuguese localization
- DevToys now has Portuguese localization
DevToys in Portuguese (Portugal)
> Added Portuguese (Portugal) localization files

- README.md
Issue Number: #131
While sharing DevToys under MIT license, we asked in the README not to sell the app without any change. We can't `enforce` it, as it cause a contradiction with the license itself.
We now `suggest` someone who intend to do this to come chat with us first.
> Updated license notice in README

- src/dev/impl/DevToys/Strings/id-ID/AllTools.resw
- src/dev/impl/DevToys/Strings/id-ID/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/id-ID/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/id-ID/Common.resw
- src/dev/impl/DevToys/Strings/id-ID/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/id-ID/HashGenerator.resw
- src/dev/impl/DevToys/Strings/id-ID/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/id-ID/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/id-ID/JsonYaml.resw
- src/dev/impl/DevToys/Strings/id-ID/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/id-ID/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/id-ID/MainPage.resw
- src/dev/impl/DevToys/Strings/id-ID/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/id-ID/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/id-ID/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/id-ID/RegEx.resw
- src/dev/impl/DevToys/Strings/id-ID/SearchResult.resw
- src/dev/impl/DevToys/Strings/id-ID/Settings.resw
- src/dev/impl/DevToys/Strings/id-ID/StringUtilities.resw
- src/dev/impl/DevToys/Strings/id-ID/TextDiff.resw
- src/dev/impl/DevToys/Strings/id-ID/ToolGroups.resw
- src/dev/impl/DevToys/Strings/id-ID/UrlEncoderDecoder.resw
- Adding Indonesian Translation
> add Indonesia translate

- src/dev/impl/DevToys/Strings/es-AR/AllTools.resw
- src/dev/impl/DevToys/Strings/es-AR/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/es-AR/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/es-AR/Common.resw
- src/dev/impl/DevToys/Strings/es-AR/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/es-AR/HashGenerator.resw
- src/dev/impl/DevToys/Strings/es-AR/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/es-AR/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/es-AR/JsonYaml.resw
- src/dev/impl/DevToys/Strings/es-AR/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/es-AR/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/es-AR/MainPage.resw
- src/dev/impl/DevToys/Strings/es-AR/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/es-AR/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/es-AR/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/es-AR/RegEx.resw
- src/dev/impl/DevToys/Strings/es-AR/SearchResult.resw
- src/dev/impl/DevToys/Strings/es-AR/Settings.resw
- src/dev/impl/DevToys/Strings/es-AR/StringUtilities.resw
- src/dev/impl/DevToys/Strings/es-AR/TextDiff.resw
- src/dev/impl/DevToys/Strings/es-AR/ToolGroups.resw
- src/dev/impl/DevToys/Strings/es-AR/UrlEncoderDecoder.resw
- [ x] Internationalization and localization
- Added (argentine) spanish translation (es-AR)
> Added (Argentine) Spanish translation resources

- src/dev/impl/DevToys/Strings/de-DE/AllTools.resw
- src/dev/impl/DevToys/Strings/de-DE/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/de-DE/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/de-DE/Common.resw
- src/dev/impl/DevToys/Strings/de-DE/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/de-DE/HashGenerator.resw
- src/dev/impl/DevToys/Strings/de-DE/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/de-DE/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/de-DE/JsonYaml.resw
- src/dev/impl/DevToys/Strings/de-DE/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/de-DE/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/de-DE/MainPage.resw
- src/dev/impl/DevToys/Strings/de-DE/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/de-DE/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/de-DE/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/de-DE/RegEx.resw
- src/dev/impl/DevToys/Strings/de-DE/SearchResult.resw
- src/dev/impl/DevToys/Strings/de-DE/Settings.resw
- src/dev/impl/DevToys/Strings/de-DE/StringUtilities.resw
- src/dev/impl/DevToys/Strings/de-DE/TextDiff.resw
- src/dev/impl/DevToys/Strings/de-DE/ToolGroups.resw
- src/dev/impl/DevToys/Strings/de-DE/UrlEncoderDecoder.resw
No German Translation
- German translation for existing tools, main page and settings
> Add German (Germany) translation resources

- src/dev/impl/DevToys/Strings/es-ES/AllTools.resw
- src/dev/impl/DevToys/Strings/es-ES/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/es-ES/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/es-ES/Common.resw
- src/dev/impl/DevToys/Strings/es-ES/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/es-ES/HashGenerator.resw
- src/dev/impl/DevToys/Strings/es-ES/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/es-ES/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/es-ES/JsonYaml.resw
- src/dev/impl/DevToys/Strings/es-ES/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/es-ES/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/es-ES/MainPage.resw
- src/dev/impl/DevToys/Strings/es-ES/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/es-ES/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/es-ES/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/es-ES/RegEx.resw
- src/dev/impl/DevToys/Strings/es-ES/SearchResult.resw
- src/dev/impl/DevToys/Strings/es-ES/Settings.resw
- src/dev/impl/DevToys/Strings/es-ES/StringUtilities.resw
- src/dev/impl/DevToys/Strings/es-ES/TextDiff.resw
- src/dev/impl/DevToys/Strings/es-ES/ToolGroups.resw
- src/dev/impl/DevToys/Strings/es-ES/UrlEncoderDecoder.resw
-
-
-
Added (Spain) Spanish translation (es-ES)
> Added Spanish (Spain) translation resources

- src/dev/impl/DevToys/Strings/pt-PT/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/pt-PT/LoremIpsumGenerator.resw
- Some new tools are not translated.
- All tools are translated to Portuguese.
> Updated Portuguese translation [pt-PT]

- src/dev/impl/DevToys/Strings/pl-PL/AllTools.resw
- src/dev/impl/DevToys/Strings/pl-PL/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pl-PL/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/pl-PL/Common.resw
- src/dev/impl/DevToys/Strings/pl-PL/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/pl-PL/HashGenerator.resw
- src/dev/impl/DevToys/Strings/pl-PL/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pl-PL/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/pl-PL/JsonYaml.resw
- src/dev/impl/DevToys/Strings/pl-PL/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/pl-PL/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/pl-PL/MainPage.resw
- src/dev/impl/DevToys/Strings/pl-PL/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/pl-PL/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/pl-PL/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/pl-PL/RegEx.resw
- src/dev/impl/DevToys/Strings/pl-PL/SearchResult.resw
- src/dev/impl/DevToys/Strings/pl-PL/Settings.resw
- src/dev/impl/DevToys/Strings/pl-PL/StringUtilities.resw
- src/dev/impl/DevToys/Strings/pl-PL/TextDiff.resw
- src/dev/impl/DevToys/Strings/pl-PL/ToolGroups.resw
- src/dev/impl/DevToys/Strings/pl-PL/UrlEncoderDecoder.resw
- src/dev/impl/DevToys/Views/Tools/Settings/MarkdownContentDialog.xaml
> Added Polish translations

- src/dev/DevToys.Startup/Package.appxmanifest
- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/Strings/hu-HU/AllTools.resw
- src/dev/impl/DevToys/Strings/hu-HU/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/hu-HU/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/hu-HU/Common.resw
- src/dev/impl/DevToys/Strings/hu-HU/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/hu-HU/HashGenerator.resw
- src/dev/impl/DevToys/Strings/hu-HU/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/hu-HU/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/hu-HU/JsonYaml.resw
- src/dev/impl/DevToys/Strings/hu-HU/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/hu-HU/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/hu-HU/MainPage.resw
- src/dev/impl/DevToys/Strings/hu-HU/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/hu-HU/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/hu-HU/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/hu-HU/RegEx.resw
- src/dev/impl/DevToys/Strings/hu-HU/SearchResult.resw
- src/dev/impl/DevToys/Strings/hu-HU/Settings.resw
- src/dev/impl/DevToys/Strings/hu-HU/StringUtilities.resw
- src/dev/impl/DevToys/Strings/hu-HU/TextDiff.resw
- src/dev/impl/DevToys/Strings/hu-HU/ToolGroups.resw
- src/dev/impl/DevToys/Strings/hu-HU/UrlEncoderDecoder.resw
- Full Hungarian translation
-
-
> Added Hungarian translations

- README.md
DevToys requires `Use all system resources` for some tools, but there's no explanation at why.
Issue Number: #206 and #208
Updated README to include it.
> Added App Permission section to Readme

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/Strings/zh-Hant/AllTools.resw
- src/dev/impl/DevToys/Strings/zh-Hant/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-Hant/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/zh-Hant/Common.resw
- src/dev/impl/DevToys/Strings/zh-Hant/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hant/HashGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hant/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-Hant/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/zh-Hant/JsonYaml.resw
- src/dev/impl/DevToys/Strings/zh-Hant/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/zh-Hant/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hant/MainPage.resw
- src/dev/impl/DevToys/Strings/zh-Hant/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/zh-Hant/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/zh-Hant/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/zh-Hant/RegEx.resw
- src/dev/impl/DevToys/Strings/zh-Hant/SearchResult.resw
- src/dev/impl/DevToys/Strings/zh-Hant/Settings.resw
- src/dev/impl/DevToys/Strings/zh-Hant/StringUtilities.resw
- src/dev/impl/DevToys/Strings/zh-Hant/TextDiff.resw
- src/dev/impl/DevToys/Strings/zh-Hant/ToolGroups.resw
- src/dev/impl/DevToys/Strings/zh-Hant/UrlEncoderDecoder.resw
> Add Traditional Chinese translation

- README.md
> Typo Found!

- src/dev/impl/DevToys/Helpers/NumberBaseHelper.cs
- src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/JsonYamlToolViewModel.cs
Fixed typo in JsonToYaml exception handler.
> Fixed typo in exception handler

- src/dev/impl/DevToys/Strings/ja-JP/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ja-JP/Settings.resw
- Update japanese translation.
-
-
> Update japanese translation.

- src/dev/impl/DevToys/Strings/it-IT/AllTools.resw
- src/dev/impl/DevToys/Strings/it-IT/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/it-IT/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/it-IT/Common.resw
- src/dev/impl/DevToys/Strings/it-IT/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/it-IT/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/it-IT/HashGenerator.resw
- src/dev/impl/DevToys/Strings/it-IT/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/it-IT/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/it-IT/JsonYaml.resw
- src/dev/impl/DevToys/Strings/it-IT/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/it-IT/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/it-IT/MainPage.resw
- src/dev/impl/DevToys/Strings/it-IT/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/it-IT/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/it-IT/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/it-IT/RegEx.resw
- src/dev/impl/DevToys/Strings/it-IT/SearchResult.resw
- src/dev/impl/DevToys/Strings/it-IT/Settings.resw
- src/dev/impl/DevToys/Strings/it-IT/StringUtilities.resw
- src/dev/impl/DevToys/Strings/it-IT/TextDiff.resw
- src/dev/impl/DevToys/Strings/it-IT/ToolGroups.resw
- src/dev/impl/DevToys/Strings/it-IT/UrlEncoderDecoder.resw
No Italian translation.
- Added the Italian translation to the strings of the app.
-
-
> Add Italian translation

- src/dev/impl/DevToys/Strings/zh-Hans/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-Hans/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/zh-Hans/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-Hans/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hans/HashGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hans/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-Hans/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/zh-Hans/JsonYaml.resw
- src/dev/impl/DevToys/Strings/zh-Hans/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/zh-Hans/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hans/MainPage.resw
- src/dev/impl/DevToys/Strings/zh-Hans/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/zh-Hans/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/zh-Hans/RegEx.resw
- src/dev/impl/DevToys/Strings/zh-Hans/Settings.resw
- src/dev/impl/DevToys/Strings/zh-Hans/UrlEncoderDecoder.resw
Chinese translation is outdated.
- All new strings are translated.
- Fixed a symbol typo. ”开始“菜单 -> “开始”菜单
- Improved existing Chinese translations by adding spacing between Chinese and English words.
> Update Chinese Translation

- src/dev/impl/DevToys/Strings/pt-PT/GZipEncoderDecoder.resw
Add pt-pt resw file for the Gzip Encoder/Decoder tool
> Add GZipEncoderDecoder pt-pt translation

- src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
Add pt-pt resw file for the Image Converter tool
> Add Image Converter pt-pt translation 

- src/dev/impl/DevToys/Helpers/NumberBaseHelper.cs
- src/dev/impl/DevToys/Strings/es-ES/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/es-ES/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/es-ES/JsonYaml.resw
- src/dev/impl/DevToys/Strings/es-ES/RegEx.resw
Some of tools translations were not correct or with incorrect casing.
> Fix some missing or wrong i18n es-ES strings

- src/dev/impl/DevToys/Strings/es-ES/GZipEncoderDecoder.resw
Spanish translation of GZip Encoder tool
> Add GZipEncoderDecoder es-ES translation

- src/dev/impl/DevToys/Strings/cs-CZ/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/cs-CZ/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/Common.resw
- src/dev/impl/DevToys/Strings/cs-CZ/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/cs-CZ/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/HashGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/cs-CZ/ImageConverter.resw
- src/dev/impl/DevToys/Strings/cs-CZ/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/cs-CZ/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/cs-CZ/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/cs-CZ/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/cs-CZ/RegEx.resw
- src/dev/impl/DevToys/Strings/cs-CZ/Settings.resw
- src/dev/impl/DevToys/Strings/cs-CZ/UrlEncoderDecoder.resw
- Missing translation for some values
- Missing translation for:
- Checksum Generator
- Color Blindness Simulator
- GZip Encoder Decoder
- Image Converter
- Lorem Ipsum Generator
- Unified translation in Number Base Converter
- Corrected a few incorrect words
- Added all missing translations
> Updated Czech localization

- src/dev/impl/DevToys/Strings/ja-JP/CheckSumGenerator.resw
- Update japanese translation.
> Update japanese translation.(CheckSum generator)

- src/dev/impl/DevToys/Strings/ja-JP/ImageConverter.resw
Issue Number: #327
- Update japanese translation. (Image Converter tool)
> Update japanese translation. (Image Converter tool)

- src/dev/impl/DevToys/Strings/it-IT/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/it-IT/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/it-IT/Common.resw
- src/dev/impl/DevToys/Strings/it-IT/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/it-IT/MainPage.resw
- src/dev/impl/DevToys/Strings/it-IT/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/it-IT/RegEx.resw
- src/dev/impl/DevToys/Strings/it-IT/Settings.resw
- src/dev/impl/DevToys/Strings/it-IT/StringUtilities.resw
- src/dev/impl/DevToys/Strings/it-IT/TextDiff.resw
- src/dev/impl/DevToys/Strings/it-IT/XmlFormatter.resw
Untranslated strings 
Translated new strings & improved existing ones
-
-
-
> Updated Italian Translations

- src/dev/impl/DevToys/Strings/ja-JP/SqlFormatter.resw
- Update japanese translation.
> Update japanese translation. (SQL Formatter tool)

- README.md
- chocolatey/DevToys/devtoys.nuspec
- chocolatey/DevToys/tools/chocolateyinstall.ps1
- chocolatey/DevToys/update.ps1
- chocolatey/README.md
Only Microsoft Store or Manual installations available.
Issue Number: #183 
- Chocolatey installation method available.
> Chocolatey support

- src/dev/impl/DevToys/Strings/ja-JP/AllTools.resw
- Update Japanese translation.
> Update Japanese translation

- src/dev/impl/DevToys/Strings/ko-KR/AllTools.resw
- src/dev/impl/DevToys/Strings/ko-KR/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ko-KR/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/ko-KR/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/ko-KR/Common.resw
- src/dev/impl/DevToys/Strings/ko-KR/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ko-KR/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/ko-KR/HashGenerator.resw
- src/dev/impl/DevToys/Strings/ko-KR/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ko-KR/ImageConverter.resw
- src/dev/impl/DevToys/Strings/ko-KR/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/ko-KR/JsonYaml.resw
- src/dev/impl/DevToys/Strings/ko-KR/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/ko-KR/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/ko-KR/MainPage.resw
- src/dev/impl/DevToys/Strings/ko-KR/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/ko-KR/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/ko-KR/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/ko-KR/RegEx.resw
- src/dev/impl/DevToys/Strings/ko-KR/SearchResult.resw
- src/dev/impl/DevToys/Strings/ko-KR/Settings.resw
- src/dev/impl/DevToys/Strings/ko-KR/SqlFormatter.resw
- src/dev/impl/DevToys/Strings/ko-KR/StringUtilities.resw
- src/dev/impl/DevToys/Strings/ko-KR/TextDiff.resw
- src/dev/impl/DevToys/Strings/ko-KR/ToolGroups.resw
- src/dev/impl/DevToys/Strings/ko-KR/UrlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ko-KR/XmlFormatter.resw
new localization appears in settings section, "ko-KR"
> Add new Localization "ko-KR"

- src/dev/impl/DevToys/Strings/id-ID/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/id-ID/Common.resw
- src/dev/impl/DevToys/Strings/id-ID/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/id-ID/ImageConverter.resw
- src/dev/impl/DevToys/Strings/id-ID/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/id-ID/SqlFormatter.resw
- src/dev/impl/DevToys/Strings/id-ID/XmlFormatter.resw
- Fixed some typo translation
- Add new translation for new feature
-
> Add new translation Indonesia and fixed some typo

- init.cmd
- init.ps1
- src/dev/DevToys.Startup/DevToys.Startup.wapproj
- Added the pause command to check for compatibility and other messages. (init.cmd -> init.ps1)
- Delete duplicate import project.
> Fix import files.

- src/dev/impl/DevToys/UI/Controls/FileSelector.xaml.cs
Issue Number: #336
Fixed the bug by adding a null check.
> Fix #336 - bug when cancelling browser selection

- src/dev/impl/DevToys/Helpers/XmlHelper.cs
- src/tests/DevToys.Tests/Helpers/XmlHelperTests.cs
- [ x] Bugfix
https://github.com/veler/DevToys/issues/355
After having the xml as a string, we replace the hard coded utf-16 to whatever the user input, or removing it if it was omitted
-
-
-
> Keep original encoding in declaration

- src/dev/impl/DevToys/Strings/zh-Hant/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hant/Common.resw
- src/dev/impl/DevToys/Strings/zh-Hant/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/zh-Hant/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/zh-Hant/SqlFormatter.resw
- src/dev/impl/DevToys/Strings/zh-Hant/XmlFormatter.resw
> Update Traditional Chinese translation

- src/dev/impl/DevToys/ViewModels/Tools/Text/RegEx/RegExToolViewModel.cs
> Fix #242 - RegEx matches in multiline text don't highlight properly

- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/cs-CZ/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/de-DE/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/en-US/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/es-AR/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/es-ES/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/fr-FR/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/hu-HU/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/id-ID/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/it-IT/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/ja-JP/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/ko-KR/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/pl-PL/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/pt-PT/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/ru-RU/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hans/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hant/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/ViewModels/Tools/Generators/LoremIpsumGenerator/LoremIpsumGeneratorToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Generators/LoremIpsumGenerator/LoremIpsumGeneratorToolPage.xaml
Issue Number: https://github.com/veler/DevToys/issues/362
A new toggle option for generating Lorem ipsum. It replaces the words of the beginning of the sentence/paragraphs with 'Lorem ipsum dolor sit amet'. 
When less words in original text, text replacement is adjusts to amount of words required.
> New option to the generator that starts generation with "Lorem Ipsum dolor sit amet..."

- src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/DecimalYamlTypeResolver.cs
> Fix #387 - wrong field inferencing in yaml to json

- ci/azure-pipelines.yml
- src/Directory.Build.props
Unit Tests aren´t executed in Azure DevOps (CI) build
Issue Number: #277
- Unit Tests are executed in Azure DevOps (CI) build
> CI unit tests

- README.md
- [ ✅ ] Documentation content changes
-
-
-
> Fix README.md minor typo

- src/dev/impl/DevToys/Strings/cs-CZ/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/Common.resw
- src/dev/impl/DevToys/Strings/cs-CZ/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/cs-CZ/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/HashGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/ImageConverter.resw
- src/dev/impl/DevToys/Strings/cs-CZ/JsonYaml.resw
- src/dev/impl/DevToys/Strings/cs-CZ/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/cs-CZ/MainPage.resw
- src/dev/impl/DevToys/Strings/cs-CZ/SqlFormatter.resw
- src/dev/impl/DevToys/Strings/cs-CZ/StringUtilities.resw
- src/dev/impl/DevToys/Strings/cs-CZ/XmlFormatter.resw
- Localized newly added tools and features (favorites, pin to Start)
- Unified previous localizations
> Updated cs-CZ localization

- src/dev/impl/DevToys/Strings/ja-JP/Common.resw
- src/dev/impl/DevToys/Strings/ja-JP/LoremIpsumGenerator.resw
- Update japanese translation. (lorem ipsum , common)
todo: HashGeneratorTests may fail in `Azure Pipelines / DevToys` .
> Update japanese translation. (lorem ipsum)

- src/dev/impl/DevToys/Strings/ja-JP/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ja-JP/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/ja-JP/UrlEncoderDecoder.resw
- Update japanese translation.
> Update japanese translation. (StringEscapeUnescape)

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/cs-CZ/Timestamp.resw
- src/dev/impl/DevToys/Strings/de-DE/Timestamp.resw
- src/dev/impl/DevToys/Strings/en-US/Timestamp.resw
- src/dev/impl/DevToys/Strings/es-AR/Timestamp.resw
- src/dev/impl/DevToys/Strings/es-ES/Timestamp.resw
- src/dev/impl/DevToys/Strings/fr-FR/Timestamp.resw
- src/dev/impl/DevToys/Strings/hu-HU/Timestamp.resw
- src/dev/impl/DevToys/Strings/id-ID/Timestamp.resw
- src/dev/impl/DevToys/Strings/it-IT/Timestamp.resw
- src/dev/impl/DevToys/Strings/ja-JP/Timestamp.resw
- src/dev/impl/DevToys/Strings/ko-KR/Timestamp.resw
- src/dev/impl/DevToys/Strings/pl-PL/Timestamp.resw
- src/dev/impl/DevToys/Strings/pt-BR/Timestamp.resw
- src/dev/impl/DevToys/Strings/pt-PT/Timestamp.resw
- src/dev/impl/DevToys/Strings/ru-RU/Timestamp.resw
- src/dev/impl/DevToys/Strings/zh-Hans/Timestamp.resw
- src/dev/impl/DevToys/Strings/zh-Hant/Timestamp.resw
- src/dev/impl/DevToys/ViewModels/Tools/Converters/Timestamp/TimestampToolProvider.cs
- src/dev/impl/DevToys/ViewModels/Tools/Converters/Timestamp/TimestampToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Converters/Timestamp/TimestampToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Converters/Timestamp/TimestampToolPage.xaml.cs
Issue Number: #106
- Added a Unix Timestamp Converter
- Any field in the UI can be an input.
- Smart detection detects Timestamps and Human-readable dates.
> Added a Unix Timestamp Converter tool

- src/dev/impl/DevToys/ViewModels/Tools/Converters/Timestamp/TimestampToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Converters/Timestamp/TimestampToolPage.xaml
Issue Number: #474
- Fix leap years.
- Fix errors when setting year 0, month 0, or blank fields.
> Added handling of out-of-range numbers and leap years.

- src/dev/impl/DevToys/ViewModels/Tools/Converters/Timestamp/TimestampToolViewModel.cs
Issue Number: https://github.com/veler/DevToys/issues/477
- Fix #477
> Fix handling of out-of-range numbers and leap years.

- ci/azure-pipelines-release.yml
- src/Directory.Build.props
Issue Number: #83
Updated WinUI to version 2.7.1 so it pass validation on the Microsoft Store.
> Enabled ARM64 build

- src/dev/impl/DevToys/Strings/pt-PT/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-PT/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/pt-PT/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/pt-PT/Common.resw
- src/dev/impl/DevToys/Strings/pt-PT/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-PT/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/pt-PT/HashGenerator.resw
- src/dev/impl/DevToys/Strings/pt-PT/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-PT/ImageConverter.resw
- src/dev/impl/DevToys/Strings/pt-PT/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/pt-PT/JsonYaml.resw
- src/dev/impl/DevToys/Strings/pt-PT/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/pt-PT/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/pt-PT/MainPage.resw
- src/dev/impl/DevToys/Strings/pt-PT/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/pt-PT/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/pt-PT/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/pt-PT/RegEx.resw
- src/dev/impl/DevToys/Strings/pt-PT/Settings.resw
- src/dev/impl/DevToys/Strings/pt-PT/SqlFormatter.resw
- src/dev/impl/DevToys/Strings/pt-PT/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/pt-PT/StringUtilities.resw
- src/dev/impl/DevToys/Strings/pt-PT/TextDiff.resw
- src/dev/impl/DevToys/Strings/pt-PT/Timestamp.resw
- src/dev/impl/DevToys/Strings/pt-PT/UrlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-PT/XmlFormatter.resw
- Updated new and existing translations in Portuguese (Portugal) language
N/A
> Update Portuguese (Portugal) Translation

- src/dev/impl/DevToys/Strings/cs-CZ/Common.resw
- src/dev/impl/DevToys/Strings/de-DE/Common.resw
- src/dev/impl/DevToys/Strings/en-US/Common.resw
- src/dev/impl/DevToys/Strings/es-AR/Common.resw
- src/dev/impl/DevToys/Strings/es-ES/Common.resw
- src/dev/impl/DevToys/Strings/fr-FR/Common.resw
- src/dev/impl/DevToys/Strings/hu-HU/Common.resw
- src/dev/impl/DevToys/Strings/id-ID/Common.resw
- src/dev/impl/DevToys/Strings/it-IT/Common.resw
- src/dev/impl/DevToys/Strings/ja-JP/Common.resw
- src/dev/impl/DevToys/Strings/ko-KR/Common.resw
- src/dev/impl/DevToys/Strings/pl-PL/Common.resw
- src/dev/impl/DevToys/Strings/pt-BR/Common.resw
- src/dev/impl/DevToys/Strings/pt-PT/Common.resw
- src/dev/impl/DevToys/Strings/ru-RU/Common.resw
- src/dev/impl/DevToys/Strings/zh-Hans/Common.resw
- src/dev/impl/DevToys/Strings/zh-Hant/Common.resw
- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs
- src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs
Users can open any kind of file in the CustomTextBox and CodeEditor control. It is unclear to the user that only textual files can be opened.
Tried to make it clearer to the user that only textual files can be opened.
> Added some file types to open file dialogs.

- src/dev/impl/DevToys.MonacoEditor/CodeEditorControl/CodeEditorCore.html
- src/dev/impl/DevToys.MonacoEditor/ts-helpermethods/otherScriptsToBeOrganized.ts
> Fixed Command Palette that has a transparent background color

- ci/azure-pipelines-release.yml
> Updated Ci to use Windows 2022 image

- src/dev/impl/DevToys/App.xaml.cs
- src/dev/impl/DevToys/Views/MainPage.xaml
- src/dev/impl/DevToys/Views/Tools/Converters/JsonYaml/JsonYamlToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/Base64ImageEncoderDecoder/Base64ImageEncoderDecoderToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Formatters/JsonFormatter/JsonFormatterToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Formatters/SqlFormatter/SqlFormatterToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Formatters/XmlFormatter/XmlFormatterToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Generators/LoremIpsumGenerator/LoremIpsumGeneratorToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/MarkdownPreview/MarkdownPreviewToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/StringUtilities/StringUtilitiesToolPage.xaml
Issue Number: #330
Scrolling doesn't pass over the title anymore
> Improved the layout of many tools in "Keep on top" view.

- src/dev/impl/DevToys/DevToys.csproj
> Fix DependentUpon (XmlValidatorToolPage.xaml)

- src/dev/impl/DevToys/Strings/af-ZA/Settings.resw
- src/dev/impl/DevToys/Strings/ar-SA/Settings.resw
- src/dev/impl/DevToys/Strings/ca-ES/Settings.resw
- src/dev/impl/DevToys/Strings/da-DK/Settings.resw
- src/dev/impl/DevToys/Strings/el-GR/Settings.resw
- src/dev/impl/DevToys/Strings/en-US/Settings.resw
- src/dev/impl/DevToys/Strings/fi-FI/Settings.resw
- src/dev/impl/DevToys/Strings/he-IL/Settings.resw
- src/dev/impl/DevToys/Strings/nl-NL/Settings.resw
- src/dev/impl/DevToys/Strings/no-NO/Settings.resw
- src/dev/impl/DevToys/Strings/ro-RO/Settings.resw
- src/dev/impl/DevToys/Strings/sr-SP/Settings.resw
- src/dev/impl/DevToys/Strings/sv-SE/Settings.resw
- src/dev/impl/DevToys/Strings/tr-TR/Settings.resw
Changes "App Theme" to "App theme" to be consistent with other options on the Settings page.
> Fixed inconsistent casing in the Settings page

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/Helpers/JsonYaml/Core/BooleanYamlTypeResolver.cs
- src/dev/impl/DevToys/Helpers/JsonYaml/JsonHelper.cs
> Fix in YAML to JSON involving boolean conversion

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Models/ColorPickerModeDisplayPair.cs
- src/dev/impl/DevToys/Models/IndentationDisplayPair.cs
- src/dev/impl/DevToys/Strings/en-US/ColorPicker.resw
- src/dev/impl/DevToys/UI/Converters/ColorToBrushConverter.cs
- src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/JsonYamlToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/Graphic/ColorPicker/ColorPickerToolProvider.cs
- src/dev/impl/DevToys/ViewModels/Tools/Graphic/ColorPicker/ColorPickerToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Graphic/ColorPicker/ColorPickerToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Graphic/ColorPicker/ColorPickerToolPage.xaml.cs
Users asked for a simple color picker tool. This PR adds one.
> Added a Color Picker tool

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/en-US/ColorPicker.resw
- src/dev/impl/DevToys/Themes/Generic.xaml
- src/dev/impl/DevToys/UI/Converters/BooleanToBrushConverter.cs
- src/dev/impl/DevToys/UI/Converters/BooleanToStringConverter.cs
- src/dev/impl/DevToys/UI/Extensions/ControlSizeTrigger.cs
- src/dev/impl/DevToys/ViewModels/Tools/Graphic/ColorPicker/ColorPickerToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Graphic/ColorPicker/ColorPickerToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Graphic/PngJpgCompressor/PngJpgCompressorToolPage.xaml
> Added contrast ratio checker

- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/StandardSqlFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/TSqlFormatter.cs
- [*] Bugfix
Issue Number: #601
-
-
-
> Adds string types for nvarchar and brackets that were missing

- src/dev/impl/DevToys/Helpers/JsonYaml/JsonHelper.cs
- src/tests/DevToys.Tests/Helpers/JsonHelperTests.cs
Issue Number: #603 
It now sort array values.
> JSON Formatter was not sorting array values.

- CODE-OF-CONDUCT.md
Issue Number: #228
- Added a Code of Conduct
> Added Code of Conduct

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/enhancement_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
Issue Number: #288, #674
Updated the GitHub templates to make them easier to fill and more relevant to us.
> Updated GitHub templates

- src/app/dev/DevToys.Localization/Strings/MainWindow/MainWindow.Designer.cs
- src/app/dev/DevToys.Localization/Strings/MainWindow/MainWindow.resx
- src/app/dev/DevToys.UI.Framework/Controls/BackdropPage.cs
- src/app/dev/DevToys.UI.Framework/Controls/BackdropWindow/BackdropWindow.MacCatalyst.cs
- src/app/dev/DevToys.UI.Framework/Controls/BackdropWindow/BackdropWindow.Wasm.cs
- src/app/dev/DevToys.UI.Framework/Controls/BackdropWindow/BackdropWindow.Windows.cs
- src/app/dev/DevToys.UI.Framework/Controls/BackdropWindow/BackdropWindow.cs
- src/app/dev/DevToys.UI/Views/MainWindow.xaml.cs
Issue Number: Closes #291
We now display the group or tool title in the task bar.
> Show current page title in TaskBar

- src/dev/DevToys.Startup/Package.appxmanifest
> Don't register as file picker

- .nuke/build.schema.json
- src/DevToys-MacOS.sln
- src/DevToys-Windows.sln
- src/app/dev/DevToys.Blazor/DevToys.Blazor.csproj
- src/app/dev/DevToys.Core/Mef/MefComposer.cs
- src/app/dev/DevToys.Core/Mef/RecursiveDirectoryCatalog.cs
- src/app/dev/DevToys.Tools/DevToys.Tools.csproj
- src/app/dev/Directory.Build.props
- src/app/dev/platforms/desktop/DevToys.CLI/DevToys.CLI.csproj
- src/app/dev/platforms/desktop/DevToys.CLI/Program.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/Core/FileStorage.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/DevToys.MacOS.csproj
- src/app/dev/platforms/desktop/DevToys.MacOS/MauiProgram.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/Platforms/MacCatalyst/AppDelegate.cs
- src/app/dev/platforms/desktop/DevToys.Windows/DevToys.Windows.csproj
- src/app/dev/platforms/desktop/DevToys.Windows/MainWindow.xaml.cs
- src/app/dev/platforms/desktop/Directory.Build.props
- src/app/dev/platforms/desktop/Directory.Build.targets
- src/app/dev/shared/LinkerConfig.xml
- src/build/Build.cs
Brought back support of plugins on Mac, Windows and Linux.
> Brought back support of plugins on Mac, Windows and Linux.

- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/CertificateEncoderDecoder/CertificateEncoderDecoderToolViewModel.cs
> Add .CRT extension to Certificate Encoder / Decoder

- src/app/dev/DevToys.Tools/Models/EncodingConversion.cs
- src/app/dev/DevToys.Tools/Tools/EncodersDecoders/Base64Text/Base64TextEncoderDecoderCommandLineTool.cs
- src/app/dev/DevToys.Tools/Tools/EncodersDecoders/Base64Text/Base64TextEncoderDecoderGuiTool.cs
N/A
Addressed some feedback from the previous PR https://github.com/veler/DevToys/pull/902
> Refactoring on Base64 Text Encoder / Decoder

- src/app/dev/DevToys.Blazor/Assets/sass/theme/_default.scss
- src/app/dev/DevToys.Blazor/Assets/sass/theme/macos/dark.scss
- src/app/dev/DevToys.Blazor/Assets/sass/theme/windows/dark.scss
- src/app/dev/DevToys.Blazor/Components/BasicInput/ToggleSwitch/ToggleSwitch.razor.scss
- src/app/dev/DevToys.Blazor/Components/Collections/ListBox/ListBoxItem.razor.scss
- src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/MonacoEditor.razor.scss
- src/app/dev/DevToys.Blazor/Components/Text/TextBox/TextBox.razor.scss
This PR updates the dark theme of DevToys on MacOS
> [DevToys 2.0] Updated dark theme for MacOS

- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/en-US/PasswordGenerator.resw
- src/dev/impl/DevToys/ViewModels/Tools/Generators/PasswordGenerator/PasswordGeneratorToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Generators/PasswordGenerator/PasswordGeneratorPage.xaml
The password generator works as normal but doesn't have the functionality to exclude characters
Issue Number: #905 
The password generator has now a extra input field where the user can specify characters to exclude from the password generator. It's seperated via comma's.
It isn't finished yet and can someone help me how to add translation functionality, because the ui code part of the input field currently looks like this:
```
<controls:CustomTextBox
Header="Exclude Characters"
IsReadOnly="False"
Text="{x:Bind ViewModel.ExcludedCharacters, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"/>
```
I don't really understand how the translation stuff works so it would be nice if someone could explain how to do it.
> Added excluding characters for password generator! #905

- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoder.cs
> Fix typo in JwtDecoder.cs

- THIRD-PARTY-NOTICES.md
- src/Directory.Packages.props
- src/app/dev/DevToys.Api/Tool/CLI/ConsoleProgressBar.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIGrid.cs
- src/app/dev/DevToys.Blazor/Components/BasicInput/Button/Button.razor.scss
- src/app/dev/DevToys.Blazor/wwwroot/js/simplebar-modified.js
- src/app/dev/platforms/desktop/DevToys.MacOS/Controls/BlazorWebView/BlazorWKWebView.cs
In DevToys 2.0 our Third Party Notice wasn't up to date.
Updated it.
> Updated third party notice

- src/app/dev/DevToys.Blazor/Pages/Index.razor
- src/app/dev/DevToys.Core/TitleBarInfoProvider.cs
- src/app/dev/platforms/desktop/DevToys.Linux/MainWindow.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/Views/MainWindow.cs
- src/app/dev/platforms/desktop/DevToys.Windows/MainWindow.xaml
#291
We now display the current tool / group in the task bar.
> Show current page in TaskBar

- src/app/dev/DevToys.Blazor/BuiltInTools/Settings/Settings.Designer.cs
- src/app/dev/DevToys.Blazor/BuiltInTools/Settings/Settings.resx
- src/app/dev/DevToys.Blazor/BuiltInTools/Settings/SettingsGuiTool.cs
Let's credit @ObuchiYuki in the Settings page.
> Credit DevToysMac author in Settings

- src/Directory.Packages.props
- https://github.com/advisories/GHSA-5x7m-6737-26cr
- https://github.com/advisories/GHSA-g85r-6x2q-45w7
-
`ZXing.Net.Bindings.ImageSharp.V3` referenced by DevToys.Tools also has a dependency.
need to wait until the package is updated.
> Bump SixLabors.ImageSharp from 3.1.3 to 3.1.4

- src/app/dev/DevToys.Blazor/BuiltInTools/ExtensionsManager/ExtensionsManager.de-DE.resx
- src/app/dev/DevToys.Blazor/BuiltInTools/Settings/Settings.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/FirstStartDialog/FirstStartDialog.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/InfoBar/InfoBar.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/MainWindow/MainWindow.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/TextBox/TextBox.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/ToggleSwitch/ToggleSwitch.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/ToolGroupPage/ToolGroupPage.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/ToolPage/ToolPage.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/UIDataGrid/UIDataGrid.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/UIFileSelectorPresenter/UIFileSelectorPresenter.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/UIImageViewer/UIImageViewer.de-DE.resx
- src/app/dev/DevToys.Localization/Strings/UITextInputWrapper/UITextInputWrapper.de-DE.resx
> German Translation

- src/app/dev/platforms/desktop/DevToys.Linux/Strings/Other/Other.de-DE.resx
- src/app/dev/platforms/desktop/DevToys.Windows/Strings/Other/Other.de-DE.resx
- src/app/dev/platforms/desktop/DevToys.Windows/Strings/TaskBar/TaskBar.de-DE.resx
> Sorry i forgot some Files (De_Translation)

- CONTRIBUTING.md
> Add same page link.

- src/Directory.Packages.props
- src/app/dev/platforms/desktop/DevToys.Linux/Components/BlazorWebView/BlazorWebViewBridge.cs
- src/app/dev/platforms/desktop/DevToys.Linux/MainWindow.cs
- src/app/dev/platforms/desktop/DevToys.Linux/Program.cs
> GirCore: Update to 0.5.0

- init.ps1
- src/Directory.Build.targets
- tools/enable-long-paths.reg
Issue Number: #1167
We now try to detect whether `LongPath` is enabled on Windows or not.
> Detect LongPath enabled on Windows

- src/app/dev/platforms/desktop/DevToys.Windows/app.manifest
Issue Number: #1200
Added DPI awareness support in Windows app manifest.
I test the change with various UI scale and it looks good.
> Add DPI awareness in WPF app. fix #1200

- .vscode/tasks.json
I'm using vscode on linux and wanted a shortcut to run the app from the tasks panel
> add run Linux, MacOS and Windows to tasks.json

- README.md
> FIx typo in README.md

- src/generators/ResxHelperGenerator/CultureHelperGenerator.cs
Issue Number: #1254
Found out that a condition in `ResxHelperGenerator` was preventing chinese languages to be available.
> Fixed a bug where Chinese language were unavailable

- README.md
Preview: https://github.com/0x5bfa/DevToys/blob/baf30b96b17a91a8af302dd4e36f50f816547bfe/README.md
> Docs: Removed underline from anchor

- src/app/dev/platforms/desktop/DevToys.Windows/Controls/MicaWindowWithOverlay.xaml
- src/app/dev/platforms/desktop/DevToys.Windows/Controls/MicaWindowWithOverlay.xaml.cs
> [Windows] fixed a bug where title bar's background color was misaligned

- src/app/dev/platforms/desktop/DevToys.Windows/MainWindow.xaml.cs
Issue Number: #1315 
We now check whether the window is within the screen boundaries.
> [Windows] the window may be off screen after unplugging a monitor

- src/app/dev/DevToys.Blazor/BuiltInTools/ExtensionsManager/ExtensionInstallationManager.cs
Nuget API requires the package name to be in lowercase. The URL we were generating didn't have the package name in lowercase.
It is not in lowercase.
> Fixed a bug in extension update check test

- src/Directory.Packages.props
Issue Number: #1410
Updated many nuget packages to address vulnerabilities
> Fixed NuGet vulnerabilities

- src/app/dev/DevToys.Blazor/Components/Menu/NavBar/NavBar.razor
- src/app/dev/platforms/desktop/DevToys.Windows/Controls/MicaWindowWithOverlay.xaml
- src/app/dev/platforms/desktop/DevToys.Windows/Controls/MicaWindowWithOverlay.xaml.cs
Issue Number: #1413
Increase margin around the window content.
> Increase window resizable area on Windows #1413

- src/app/dev/DevToys.Blazor/BuiltInTools/Settings/Settings.Designer.cs
- src/app/dev/DevToys.Blazor/BuiltInTools/Settings/Settings.resx
- src/app/dev/DevToys.Blazor/BuiltInTools/Settings/SettingsGuiTool.cs
- src/app/dev/DevToys.Core/Settings/PredefinedSettings.cs
- src/app/dev/DevToys.Core/Tools/GuiToolProvider.cs
Issue Number: fix #1404
Added an option to show recent tools. The option is ON by default.
> Added an option to disable recent tools

- src/app/dev/platforms/desktop/DevToys.Linux/Components/BlazorWebView/BlazorWebView.cs
Issue Number: fix #1446
[Similarly to MacOS](https://github.com/DevToys-app/DevToys/pull/1284), solved the issue by change the URL we point to from `app://0.0.0.0` to `app://localhost`.
> Fixed blank window on Linux
