- src/dev/impl/DevToys/Views/MainPage.xaml.cs
When the app starts with NavigationView in Compact mode, the layout seems broken and Monaco Editor can't be focused until the app goes to Expanded mode (and goes back to Compact, if wanted).
Issue Number: #54 
Fixed the issue by forcing the view to start in Expanded view, and then switch to Compact view is needed.
> Fixed a bug where Monaco Editor isn't clickable when NavigationView is in Compact state.

- README.md
- src/dev/impl/DevToys/Api/Core/IMarketingService.cs
- src/dev/impl/DevToys/App.xaml.cs
- src/dev/impl/DevToys/Core/MarketingService.cs
- src/dev/impl/DevToys/Core/Threading/AsyncLazy.cs
- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Models/MarketingState.cs
- src/dev/impl/DevToys/Strings/cs-CZ/MainPage.resw
- src/dev/impl/DevToys/Strings/en-US/MainPage.resw
- src/dev/impl/DevToys/Strings/fr-FR/MainPage.resw
- src/dev/impl/DevToys/Strings/ru-RU/MainPage.resw
- src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/Base64EncoderDecoder/Base64EncoderDecoderToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/GuidGenerator/GuidGeneratorToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/HashGenerator/HashGeneratorToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/JsonFormatter/JsonFormatterToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/JsonYaml/JsonYamlToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/JwtDecoderEncoder/JwtDecoderEncoderToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/MarkdownPreview/MarkdownPreviewToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/RegEx/RegExToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/StringUtilities/StringUtilitiesToolViewModel.cs
DevToys is unable to automatically offer the user to rate the app at some key moments that would encourage the user to give a high rating.
Issue Number: #57
The app will automatically display a notification offering the user to rate the app based on the following criteria:
1. The app hasn't been rated yet
2. We have offered the user to rate the app less than 11 times.
3. It's been at least 8 days that the users installed the app or used it since the last crash encountered.
4. The app has been launched at least 4 times since it's installed or since the last crash encountered.
5. The app has updated more than 2 days ago.
6. Smart detection has recommended tools at least 3 times in the past
7. Users used tools at least 10 times in the past. …
> Added a way to automatically offer the user to rate the app

- CONTRIBUTING.md
> Added more documentation to CONTRIBUTING.md

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/Helpers/NumberBaseHelper.cs
- src/dev/impl/DevToys/ViewModels/Tools/NumberBaseConverter/NumberBaseConverterToolProvider.cs
- src/dev/impl/DevToys/Views/Tools/NumberBaseConverter/NumberBaseConverterToolPage.xaml.cs
If the user has a content in is clipboard that can be treated by the Number Base Converter, the toy is not highlighted.
Issue Number: #87 
If the user has a content in is clipboard that can be treated by the Number Base Converter.
- the toy will be highlighted.
- if it's the only toy that can handle this content, it will be loaded
- the clipboard content will be past and the matching input will be selected
> Number Base Converter smart detection for Hexadecimal and Binary

- src/dev/impl/DevToys.OutOfProcService/API/Core/OOP/IOutOfProcService.cs
- src/dev/impl/DevToys.OutOfProcService/Core/OOP/AppService.cs
- src/dev/impl/DevToys.OutOfProcService/OutOfProcServices/OutOfProcServiceBase.cs
- src/dev/impl/DevToys.OutOfProcService/OutOfProcServices/ShutdownService.cs
- src/dev/impl/DevToys/Api/Core/OOP/IAppService.cs
- src/dev/impl/DevToys/Core/OOP/AppService.cs
After using the Win32 app service (through PNG / JPEG Compressor tool, for example), when closing DevToys, the UWP process takes several seconds to stop and end up on a crash.
Issue Number: #94
The issue is caused by the Shutdown AppService message. In short, this message shut down the Win32 app. Meanwhile, DevToys' UWP app is waiting for an answer from the Win32 process. Since the process shut down, there's no answer to expect.
The fix is to allow to send a message to the Win32 app without expecting any response.
> Fixes #94 where DevToys takes several seconds to shutdown after using PNG / JPEG Compressor tool.

- src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
- src/dev/impl/DevToys/Views/MainPage.xaml
The hamburger menu only appears when the app is in compact or minimal size, making it impossible to collapse the menu when the window is in large.
Issue Number: #99
The hamburger is now always shown except in Compact Overlay mode.
> Made the main menu always collapsible.

- src/dev/impl/DevToys/Api/Tools/MatchedToolProvider.cs
- src/dev/impl/DevToys/Core/Collections/ExtendedObservableCollection.cs
- src/dev/impl/DevToys/Core/ToolProviderFactory.cs
- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Models/NoResultFoundMockToolProvider.cs
- src/dev/impl/DevToys/Strings/cs-CZ/MainPage.resw
- src/dev/impl/DevToys/Strings/en-US/MainPage.resw
- src/dev/impl/DevToys/Strings/fr-FR/MainPage.resw
- src/dev/impl/DevToys/Strings/pl-PL/MainPage.resw
- src/dev/impl/DevToys/Strings/ru-RU/MainPage.resw
- src/dev/impl/DevToys/Strings/zh-CN/MainPage.resw
- src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/Text/Formatters/FormattersGroupToolProvider.cs
- src/dev/impl/DevToys/Views/MainPage.xaml
Since changes in PR #104, the search box was not doing anything anymore.
Issue Number: #88 
Search is operational again. However the behavior changed and there is some remaining work to do.
Done:
- Search show the result in a combo list.
- Selecting a matching item navigates to it.
- Typing something that gives no result shows an item "No results found".
To do in a future PR:
- Clicking on "No results found" item or pressing [Enter] when there's no result should go to a page indicating that there is no result.
- Pressing [Enter] when the typed query gives several suggested items should go to a page showing details about these suggested items.
> Moved search results to AutoSuggestedBox instead of NavigationView

- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Models/NumberBaseFormat.cs
- src/dev/impl/DevToys/Strings/cs-CZ/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/en-US/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/fr-FR/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/pl-PL/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/ru-RU/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/zh-CN/NumberBaseConverter.resw
- src/dev/impl/DevToys/ViewModels/Tools/NumberBaseConverter/NumberBaseConverterToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/NumberBaseConverter/NumberBaseFormatter.cs
- src/tests/DevToys.Tests/Core/Formatter/BaseNumberFormatterTests.cs
The user can type any character in the input field
If the user type an invalid character in the input field. The user will see a localized error message.
- [] Verified that the change work in Release build configuration
> Added localized error message and error parsing for base number type

- src/dev/impl/DevToys/ViewModels/Tools/ToolProviderBase.cs
When the NavigationView is collapsed, SVG icons may be flickering.
Fixed the issue by limiting the icon size change.
Additionally, reduced the amount of access to the hard drive when rendering the icons.
> Fixed an issue where SVG icons were flickering when the NavigationView was collapsed.

- src/dev/impl/DevToys/Api/Tools/IToolProviderFactory.cs
- src/dev/impl/DevToys/Api/Tools/MenuPlacement.cs
- src/dev/impl/DevToys/Api/Tools/MenuPlacementAttribute.cs
- src/dev/impl/DevToys/Api/Tools/NotSearchableAttribute.cs
- src/dev/impl/DevToys/Api/Tools/ToolProviderMetadata.cs
- src/dev/impl/DevToys/Core/ToolProviderFactory.cs
- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/en-US/AllTools.resw
- src/dev/impl/DevToys/UI/MainMenuNavigationViewMenuItemSelector.cs
- src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/AllTools/AllToolsToolProvider.cs
- src/dev/impl/DevToys/ViewModels/Tools/AllTools/AllToolsToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/GroupToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/GroupToolViewModelBase.cs
- src/dev/impl/DevToys/ViewModels/Tools/Settings/SettingsToolProvider.cs
- src/dev/impl/DevToys/ViewModels/Tools/ToolProviderBase.cs
- src/dev/impl/DevToys/Views/MainPage.xaml
- src/dev/impl/DevToys/Views/Tools/AllTools/AllToolsToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/AllTools/AllToolsToolPage.xaml.cs
> Added a "All tools" menu

- src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
- src/dev/impl/DevToys/Views/MainPage.xaml.cs
When the sidebar is collapse and the user click on a toys the child pane is displayed over the toys
Issue Number: #116 
When the user click on a toys when the sidebar is collapse the child pane is not displayed
> hide the child pane on compact mode

- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/Base64EncoderDecoder/Base64EncoderDecoderToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/HtmlEncoderDecoder/HtmlEncoderDecoderToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/UrlEncoderDecoder/UrlEncoderDecoderToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/Base64EncoderDecoder/Base64EncoderDecoderToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/Base64EncoderDecoder/Base64EncoderDecoderToolPage.xaml.cs
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/HtmlEncoderDecoder/HtmlEncoderDecoderToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/HtmlEncoderDecoder/HtmlEncoderDecoderToolPage.xaml.cs
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/URLEncoderDecoder/UrlEncoderDecoderToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/URLEncoderDecoder/UrlEncoderDecoderToolPage.xaml.cs
- src/tests/DevToys.Tests/Providers/Tools/Base64EncoderDecoderTests.cs
Issue Number: #154
The conversion mode is now saved in setting as a boolean instead of string, since we only have the two options encode and decode 
> Replaced all encoder/decoder tools dropdown with a toggle switch

- src/dev/impl/DevToys/Strings/en-US/NumberBaseConverter.resw
- src/dev/impl/DevToys/ViewModels/Tools/Converters/NumberBaseConverter/NumberBaseFormatter.cs
Updated ValueOverflow exception to use localised error message.
Also corrected grammar and capitalisation (for English)
Localised exception message for Number Base Converter only displays if Input Type is Decimal, this error message has poor grammar
Issue Number: #150
- Inputting a too large number will always display a localised warning message
- Warning message has better grammar
- Removed random capital in "Input" from InputTypeDescription
> Updated ValueOverflow exception to use localised error message.

- src/dev/impl/DevToys/Strings/fr-FR/ToolGroups.resw
Fix a typo in tool "Graphic", in French language
The Graphic tool is translated by "Gaphique" in french
Now, the Graphic tool is translated by "Graphique" in french
> Fixed French translation [fr-FR]

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/DecimalJsonConverter.cs
- src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/DecimalYamlTypeResolver.cs
- src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/JsonYamlToolViewModel.cs
Closes #202 
Issue Number: #202
- numbers are now converted to decimal instead of string
> Fixes numbers are converted to string in Yaml to Json conversion

- src/dev/impl/DevToys/ViewModels/Tools/Generators/CheckSumGenerator/CheckSumGeneratorToolViewModel.cs
While computation is ongoing, if you drag a second file to be processed, the loader will disappear and fail to calculate the checksum of the second inputted file.
Issue Number: Related to #141 
If a second file is dragged while a first one is being processed, the first one will be canceled and will start processing the second file.
> Fix CheckSum computation cancellation 

- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/cs-CZ/HashGenerator.resw
- src/dev/impl/DevToys/Strings/de-DE/HashGenerator.resw
- src/dev/impl/DevToys/Strings/en-US/HashGenerator.resw
- src/dev/impl/DevToys/Strings/es-AR/HashGenerator.resw
- src/dev/impl/DevToys/Strings/es-ES/HashGenerator.resw
- src/dev/impl/DevToys/Strings/fr-FR/HashGenerator.resw
- src/dev/impl/DevToys/Strings/hu-HU/HashGenerator.resw
- src/dev/impl/DevToys/Strings/id-ID/HashGenerator.resw
- src/dev/impl/DevToys/Strings/ja-JP/HashGenerator.resw
- src/dev/impl/DevToys/Strings/pl-PL/HashGenerator.resw
- src/dev/impl/DevToys/Strings/pt-PT/HashGenerator.resw
- src/dev/impl/DevToys/Strings/ru-RU/HashGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hans/HashGenerator.resw
- src/dev/impl/DevToys/ViewModels/Tools/Generators/HashGenerator/HashGeneratorToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Generators/HashGenerator/HashGeneratorToolPage.xaml
The output of a hash generation is always Hex. Sometimes is useful for the output to be in base64.
Issue Number: #239 
- An option to select the Output Type between Hex and Base64 has been added
> HashGenerator output on base64 or hex

- src/dev/impl/DevToys/ViewModels/Tools/Text/MarkdownPreview/MarkdownPreviewToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Text/MarkdownPreview/MarkdownPreviewToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/MarkdownPreview/MarkdownPreviewToolPage.xaml.cs
There is no way to copy the HTML output from the markdown preview.
A new copy button above the `Webview` control allows the user to copy the contents of the `markdown-body` element.
<details>
<summary>Screenshot</summary>
</details>
I am a newbie at UWP app development and especially with the MVVM pattern.
- I could not get this to work on my machine for some reason even though my changes should not affect the Release build config. I was getting an error about a `SetVersion` task being unable to run because `Microsoft.Build.Utilities` version `3.5.0.0` wasn't available despite having a successful Nuget restore.
> Add a copy button to the MarkdownPreview tool to copy the HTML output

- src/dev/impl/DevToys/LanguageDefinition.cs
When we have multiple language installed, the option **Language - Same as Microsoft Windows** doesn't select the Windows Display Culture.
Issue Number: #193
close #193
When we have multiple language installed, the option **Language - Same as Microsoft Windows** select the Windows Display Culture.
- [] Checked all unit tests pass
> Language - Same as Microsoft Windows

- src/dev/impl/DevToys/Strings/de-DE/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/en-US/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/es-AR/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/es-ES/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/fr-FR/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/hu-HU/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/id-ID/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/it-IT/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/pl-PL/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/ru-RU/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hans/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/zh-Hant/CheckSumGenerator.resw
Minor grammar fix, correcting the phrase "Generate _an_ hash" to "Generate _a_ hash" in the checksum generator description. This correction is made in `en-US` and replicated across another 11 localisation files that have not yet been translated.
It is not always clear in English whether 'a' or 'an' should be used before an 'h' ([some discussion](https://english.stackexchange.com/questions/629/when-should-i-use-a-versus-an-in-front-of-a-word-beginning-with-the-letter-h)). However, this particular case is [not ambiguous](https://books.google.com/ngrams/graph?content=a+hash%2Can+hash). 😊
I did not create an issue for this PR as it is trivial.
> Grammar fix: Replace "an hash" -> "a hash" in localisations

- src/dev/impl/DevToys/ViewModels/Tools/Converters/NumberBaseConverter/NumberBaseFormatter.cs
- src/tests/DevToys.Tests/Providers/Tools/BaseNumberFormatterTests.cs
Octals were not correctly validated. Any number could be passed on input and the code were not complaining about it. Any calculation with an incorrect octal resulted on a input ignore.
Number as 01234567**8** were accepted as a correct octal.
- Octal are correctly validated.
> Fix octal characters validation

- src/dev/impl/DevToys/ViewModels/Tools/Converters/JsonYaml/DecimalYamlTypeResolver.cs
The conditional at `DecimalYamlTypeResolver` is causing an `OutOfRange` exception. It tries to evaluate the latest or condition, rising an exception when `Value` is empty.
It rise an exception that is not a major issue, but is an unnecessary exception.
- No more exception for `DecimalYamlTypeResolver`
> Fix an incorrect conditional grouping that is causing an exception

- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderEncoderToolPage.xaml
The JWT Header is _generally_ much smaller than the Payload in comparison. Adding a splitter allows the user to adjust the size of the panels to focus on the panel that is most important to them.
Current behavior treats both panels as equals which makes it harder to focus on the payload.
- Added a new grid row between the Header & Payload rows to allow resizing
> Add splitter between Header & Paylod in JWT Decoder

- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/Formatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/InlineBlock.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/Params.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/RegexFactory.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/Token.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/TokenHelper.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/Tokenizer.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/Db2Formatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/MariaDbFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/MySqlFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/N1qlFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/PlSqlFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/PostgreSqlFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/RedshiftFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/SparkSqlFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/StandardSqlFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Languages/TSqlFormatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/SqlFormatterHelper.cs
- src/tests/DevToys.Tests/Providers/Tools/SqlFormatterTests.cs
this pull request contains 2 optimization 1 and 2.
- **Optimize sql-formatter (1):**
During tokenization and after a successful regex match, only the index and the length of the match are stored. So there is no new string allocations. And during formatting, a read-only span is created over the string input and the new formatted string is written using the StringBuilder.
- **Optimize sql-formatter (2):**
Removing the "Compiled" option from all regex objects has made a big difference in terms of memory and speed.
**Note:**
String-named placeholders (@"foo") are actually not originally supported in sql, so to simplify the key parsing I [removed it](https://github.com/veler/DevToys/pull/368/commits/ca52c2774be05e1a951ea5488fe74871864d501b#dif …
> Sql-formatter optimization 

- src/dev/impl/DevToys/Helpers/NumberBaseHelper.cs
- src/dev/impl/DevToys/ViewModels/Tools/Converters/NumberBaseConverter/NumberBaseConverterToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/Converters/NumberBaseConverter/NumberBaseFormatter.cs
- src/dev/impl/DevToys/Views/Tools/Converters/NumberBaseConverter/NumberBaseConverterToolPage.xaml
- src/tests/DevToys.Tests/Providers/Tools/BaseNumberFormatterTests.cs
Closes #256 but with new issue lol
At the other hand, in #256 there are some features mentioned that could conflict with these new changes. The Input field now is removed, so if you want any custom number base input, then we will need to change the interface and how it works.
You could change the numbers using any output field. Now there are some changes in the UI, as some options (number format) and Input field now become deprecated.
Issue Number: #256 
- You can use any output field as an input.
~~Now there is a new issue... I am not sure why is happening that when the input is reformatted the text cursor returns to the left of the input field. I could keep an eye on it and try to get it solved.~~
Ok, this issue was solved with a …
> Number converter fields as inputs

- src/dev/impl/DevToys/Helpers/HashingHelper.cs
- src/tests/DevToys.Tests/Helpers/HashingHelperTests.cs
This PR corrects a small byte array copying mistake in `HashingHelper`.
Issue Number: https://github.com/veler/DevToys/issues/373
Correct checksums are generated.
For example, consistency can be verified using `certUtil` on windows with something like `certutil -hashfile <filename> SHA256`
> Fix incorrect checksum issue

- src/dev/impl/DevToys/ViewModels/Tools/Generators/HashGenerator/HashGeneratorToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Generators/HashGenerator/HashGeneratorToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Generators/HashGenerator/HashGeneratorToolPage.xaml.cs
This PR disables the uppercase toggle switch if `Base64` is selected as the output type in the Hash Generator Tool.
Also refactors related if conditions in `HashGeneratorToolViewModel`
Issue Number: https://github.com/veler/DevToys/issues/395
The uppercase toggle switch becomes disabled if `Base64` is selected as the output type.
Base64 outputs are no longer converted to lower/upper-case
> Fix for incorrect base64 hashes

- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderEncoderToolProvider.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderEncoderToolViewModel.cs
Currently, if there is an empty space in the input for the JWT decoder, the decoding will fail.
Issue Number: #391
- With the fix, the input string gets trimmed, so that any empty spaces will be removed.
> Trimmed input string for the JwtDecoderEncoder

- src/dev/impl/DevToys/ViewModels/Tools/Converters/NumberBaseConverter/NumberBaseConverterToolViewModel.cs
- Fixed a bug in NumberBaseConverter that caused DevToys to quit when switching focus when the text box was empty.
> Fixed an error when the textbox of NumberBaseConverter is empty.

- src/dev/impl/DevToys/Strings/pt-BR/AllTools.resw
- src/dev/impl/DevToys/Strings/pt-BR/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-BR/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/pt-BR/ColorBlindnessSimulator.resw
- src/dev/impl/DevToys/Strings/pt-BR/Common.resw
- src/dev/impl/DevToys/Strings/pt-BR/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-BR/GuidGenerator.resw
- src/dev/impl/DevToys/Strings/pt-BR/HashGenerator.resw
- src/dev/impl/DevToys/Strings/pt-BR/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-BR/ImageConverter.resw
- src/dev/impl/DevToys/Strings/pt-BR/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/pt-BR/JsonYaml.resw
- src/dev/impl/DevToys/Strings/pt-BR/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/pt-BR/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/pt-BR/MainPage.resw
- src/dev/impl/DevToys/Strings/pt-BR/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/pt-BR/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/pt-BR/PngJpgCompressor.resw
- src/dev/impl/DevToys/Strings/pt-BR/RegEx.resw
- src/dev/impl/DevToys/Strings/pt-BR/SearchResult.resw
- src/dev/impl/DevToys/Strings/pt-BR/Settings.resw
- src/dev/impl/DevToys/Strings/pt-BR/SqlFormatter.resw
- src/dev/impl/DevToys/Strings/pt-BR/StringUtilities.resw
- src/dev/impl/DevToys/Strings/pt-BR/TextDiff.resw
- src/dev/impl/DevToys/Strings/pt-BR/ToolGroups.resw
- src/dev/impl/DevToys/Strings/pt-BR/UrlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/pt-BR/XmlFormatter.resw
- Adding files translated to Portuguese (Brazil)
> feature: :speech_balloon: add new lang (Portuguese-Brazil)

- README.md
- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/Helpers/StringManipulationHelper.cs
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/cs-CZ/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/de-DE/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/en-US/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/en-US/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/es-AR/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/es-ES/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/fr-FR/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/hu-HU/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/id-ID/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/it-IT/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/ja-JP/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/ko-KR/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/pl-PL/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/pt-PT/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/ru-RU/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/zh-Hans/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/zh-Hant/StringEscapeUnescape.resw
- src/dev/impl/DevToys/ViewModels/Tools/Text/StringEscapeUnescape/StringEscapeUnescapeToolProvider.cs
- src/dev/impl/DevToys/ViewModels/Tools/Text/StringEscapeUnescape/StringEscapeUnescapeToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Text/StringEscapeUnescape/StringEscapeUnescapeToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/StringEscapeUnescape/StringEscapeUnescapeToolPage.xaml.cs
> Added String Escape / Unescape tool

- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/Base64EncoderDecoder/Base64EncoderDecoderToolViewModel.cs
- src/tests/DevToys.Tests/Providers/Tools/Base64EncoderDecoderTests.cs
Closes #178
- [x ] Feature
Pasting a base64 string without the final '=' can not be decoded.
Issue Number: #178 
Pasting a base64 string without final '=' will add the final '=' to the data to be decoded. Input data in the form is not modified.
- [x ] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [x ] Checked all unit tests pass
> Enable decoding of unpadded base64 strings

- src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs
Issue Number: #448 
- Disabled cut command for read-only textbox.
- Added post-processing for text cut command.
Disabled cut command for read-only textbox.
This change eliminates access denied errors.
> Feature name: Failed to cut from custom text box
> Custom message: 
> Exception message: Access is denied. (Exception from HRESULT: 0x80070005)
> Exception stack trace:
>    at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
>    at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32) + 0xb8
>    at __Interop.ForwardComStubs.Stub_17[TThis](__ComObject, Int32) + 0x24
>    at Windows.UI.Text.ITextRange__Impl.Dispatcher.global::Windows.UI.Text.ITextRange.Cut() + 0x18
> …
> Fix textbox cut command

- src/dev/impl/DevToys/Strings/ko-KR/Base64EncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ko-KR/CheckSumGenerator.resw
- src/dev/impl/DevToys/Strings/ko-KR/Common.resw
- src/dev/impl/DevToys/Strings/ko-KR/ImageConverter.resw
- src/dev/impl/DevToys/Strings/ko-KR/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/ko-KR/LoremIpsumGenerator.resw
- src/dev/impl/DevToys/Strings/ko-KR/MainPage.resw
- src/dev/impl/DevToys/Strings/ko-KR/MarkdownPreview.resw
- src/dev/impl/DevToys/Strings/ko-KR/NumberBaseConverter.resw
- src/dev/impl/DevToys/Strings/ko-KR/StringEscapeUnescape.resw
- src/dev/impl/DevToys/Strings/ko-KR/Timestamp.resw
Add Korean translations for Number base converter, String escape and unescape tool and Timestamp converter tool.
Also, I translated not yet translated things in other tools and update some expressions.
- Update Korean translation (ko-KR)
> Update Korean translation "ko-KR"

- src/dev/impl/DevToys/Helpers/HashingHelper.cs
- src/tests/DevToys.Tests/Helpers/HashingHelperTests.cs
Issue Number: https://github.com/veler/DevToys/issues/469
Empty file can now have checksums generated:
1. MD5: d41d8cd98f00b204e9800998ecf8427e
2. SHA1: da39a3ee5e6b4b0d3255bfef95601890afd80709
3. SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
4. SHA384: 38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf63f6e1da274edebfe76f65fbd51ad2f14898b95b
5. SHA512: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
Tested on Windows 10 21H2, x64 (Release and Debug)
> Fixes 469 - Checksum/Hash generator doesn't accept empty file/input

- src/dev/impl/DevToys/Views/MainPage.xaml
Issue Number:
- #487
- ScrollViewerContent does not expand too much when the application screen area is small.
- So, adjusted ScrollViewerContent.Margin when VisualState is NavigationViewMinimal.
|Before|After|
---|---
|![image](https://user-images.githubusercontent.com/49768768/163592413-380b215b-2e58-4fa3-a6ca-cbf7c4f62e7c.png)|![image](https://user-images.githubusercontent.com/49768768/163594161-dfa14d1d-b6c5-4b16-982f-d4120a3ac96d.png)|
> Fixed title being hidden under header.

- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/cs-CZ/Common.resw
- src/dev/impl/DevToys/Strings/de-DE/Common.resw
- src/dev/impl/DevToys/Strings/en-US/Common.resw
- src/dev/impl/DevToys/Strings/es-AR/Common.resw
- src/dev/impl/DevToys/Strings/es-ES/Common.resw
- src/dev/impl/DevToys/Strings/fr-FR/Common.resw
- src/dev/impl/DevToys/Strings/hu-HU/Common.resw
- src/dev/impl/DevToys/Strings/id-ID/Common.resw
- src/dev/impl/DevToys/Strings/it-IT/Common.resw
- src/dev/impl/DevToys/Strings/ja-JP/Common.resw
- src/dev/impl/DevToys/Strings/ko-KR/Common.resw
- src/dev/impl/DevToys/Strings/pl-PL/Common.resw
- src/dev/impl/DevToys/Strings/pt-BR/Common.resw
- src/dev/impl/DevToys/Strings/pt-PT/Common.resw
- src/dev/impl/DevToys/Strings/ru-RU/Common.resw
- src/dev/impl/DevToys/Strings/zh-Hans/Common.resw
- src/dev/impl/DevToys/Strings/zh-Hant/Common.resw
- src/dev/impl/DevToys/ViewModels/Tools/Converters/Timestamp/TimestampToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Converters/Timestamp/TimestampToolPage.xaml
Introduces request from #483 which asks to have a Now button. The button could also be labeled "Reset", but the term "Now" is more explicit about what the button intends to do (set all times to the current date and time).
Issue Number: #483 
- Adds a "Now" button in the Timestamp converter
- Clicking the "Now" button sets time to currnet date and time and resets the display window times
- Behaves similar to how the page is initiated
- Added default transactions for "Now" button
> #483 Added Now button to bring timestamp to current date and time.

- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/Formatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/Indentation.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/SqlFormatterOptions.cs
- src/dev/impl/DevToys/ViewModels/Tools/Formatters/SqlFormatter/SqlFormatterToolViewModel.cs
- src/tests/DevToys.Tests/Providers/Tools/SqlFormatterTests.cs
- Added "One tab" indentation for SQL Formatter
> Added "One tab" indentation for SQL Formatter

- src/dev/impl/DevToys/UI/Controls/ImagePreview.xaml
Issue Number: #526 
The buttons are now hidden if there's no image visible.
> [Base64 Image] Click on save or view while no input made the app crashing

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml
- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs
- src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/Base64ImageEncoderDecoder/Base64ImageEncoderDecoderToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/Base64ImageEncoderDecoder/MockSettingsProvider.cs
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/Base64ImageEncoderDecoder/Base64ImageEncoderDecoderToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/StringUtilities/StringUtilitiesToolPage.xaml
Base64 Image Encoder / Decoder tool was using the `CustomTextBox` control which struggles with very large piece of text base64 text.
The Monaco editor is now used.
To do this change, I needed to add a property to allow showing the Copy button even if the code editor isn't read-only.
Additionally, I needed to force the control to wrap the text and hide the line number, so it acts more like a regular text box. To do this, I mocked the `ISettingsProvider` in order to override the settings representing text wrapping and line number.
As a result, encoding a large image makes the result appear instantly now.
> Changed the Base64 Image tool to use the Code editor instead of a Text box

- src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml
- src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs
- src/dev/impl/DevToys/ViewModels/Tools/Generators/GuidGenerator/GuidGeneratorToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/Generators/HashGenerator/HashGeneratorToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Generators/GuidGenerator/GuidGeneratorToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Generators/HashGenerator/HashGeneratorToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/RegEx/RegExToolPage.xaml
Allows the selected font in the settings to be applied to areas that makes sense, for example selecting a fixed width font would make the output content easier to read. 
The following tools have this applied:
- The UUID Generator output
- The Hash Generator hash outputs
- Regex tester - regex string textbox
Currently the output textbox uses the default Windows font (Segoe UI) which not a fixed width font. It is not currently possible to change this font during application use.
Issue Numbers: #153 & #290 
- `CustomTextBox` now takes note of the Font setting via the `SettingsProvider`. This allows various controls to inherit and bind to this setting.
Screenshot showing the default font Segoe UI which cannot be changed by the settings …
> Apply the font set in settings to certain output text boxes

- src/dev/impl/DevToys/Strings/ja-JP/GZipEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ja-JP/HtmlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ja-JP/JsonFormatter.resw
- src/dev/impl/DevToys/Strings/ja-JP/JsonYaml.resw
- src/dev/impl/DevToys/Strings/ja-JP/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/Strings/ja-JP/UrlEncoderDecoder.resw
- src/dev/impl/DevToys/Strings/ja-JP/XmlFormatter.resw
- Remove unnecessary strings automatically added by external services.
> fix SearchKeywords value.

- src/dev/impl/DevToys/Helpers/JsonYaml/JsonHelper.cs
- src/tests/DevToys.Tests/Helpers/JsonHelperTests.cs
Issue Number: #573
Date time are now unchanged when parsing a JSON for formatting it.
> Fixed Json Formatter altering date's time zone.

- src/dev/impl/DevToys/Helpers/JsonYaml/JsonHelper.cs
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/en-US/JsonFormatter.resw
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderEncoderToolViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/Formatters/JsonFormatter/JsonFormatterToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/Base64TextEncoderDecoder/Base64EncoderDecoderToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Formatters/JsonFormatter/JsonFormatterToolPage.xaml
- src/tests/DevToys.Tests/Helpers/JsonHelperTests.cs
In #569, a MacOS customer was asking for a way to compare 2 JSON.
This is halfway possible in the Windows DevToys app by combining JSON Formatter and Text Diff tool. One missing piece to make it fully working is sorting the JSON properties.
Added a new option to sort JSON content.
> JSON Formatter can now sort properties alphabetically.

- src/dev/impl/DevToys/Core/Settings/PredefinedSettings.cs
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/en-US/Settings.resw
- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs
- src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml
- src/dev/impl/DevToys/UI/Controls/CustomTextBox.xaml.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/Base64ImageEncoderDecoder/MockSettingsProvider.cs
- src/dev/impl/DevToys/ViewModels/Tools/Settings/SettingsToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Converters/JsonYaml/JsonYamlToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Formatters/JsonFormatter/JsonFormatterToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Formatters/SqlFormatter/SqlFormatterToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Formatters/XmlFormatter/XmlFormatterToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Generators/GuidGenerator/GuidGeneratorToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Generators/HashGenerator/HashGeneratorToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Settings/SettingsToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/MarkdownPreview/MarkdownPreviewToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/RegEx/RegExToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/TextDiff/TextDiffToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/Text/XmlValidator/XmlValidatorToolPage.xaml
Issue Number: #562
- Added a new option in the Settings allowing the user to clear the text box when pasting from the clipboard, so it replaces the content of the text box by the one from the clipboard.
- Fixed a bug where Base64 Image Encoder / Decoder doesn't update accordingly to the user settings changes.
- Applied the font settings in every text editor.
> Added an option to clear text editor when pasting from the clipboard.

- src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs
- [✓] Feature
Like discussed in [Issue 600](https://github.com/veler/DevToys/issues/600)
Even if there's multiple recommended ToolProviders, the tool selection is triggered if there's one in the favorites.
Issue Number: **600**
- [✓] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [✓] Verified that the change work in Release build configuration
- [✓] Checked all unit tests pass
> Leverage favorites for recommended tool providers

- src/dev/impl/DevToys/Helpers/JsonYaml/JsonHelper.cs
- src/tests/DevToys.Tests/Helpers/JsonHelperTests.cs
Adds appropriate test cases to JsonHelperTests
Current behavior will deserialize the Input field of the JsonFormatter as a JObject, which will work as expected for top-level values and object definitions. But when the top-level object is an array, it cannot be serialized to this type, and instead writes the exception body to the Output.
Issue Number: #620
The new behavior deserializes the Input text as a JToken, which is able to represent both JObject and JArray types. To handle sorting properties recursively, I created an overload of JsonFormatter.SortJsonPropertiesAlphabetically for JArray objects. Both methods were modified to recursively call eachother based on the property's JToken type.
> Fix JsonHelper.Format failing when deserializing top-level array objects

- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderControl.xaml
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderEncoderToolPage.xaml
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/JwtDecoderEncoder/JwtEncoderControl.xaml
JWT Encoder/Decoder uses only a fixed amount of vertical space for Payload. With short tokens this just leaves empty visual space at the bottom but for tokens with many claims it requires scrolling no matter what size the window is.
- Encoder and Decoder Page expands vertically to fill available window space
- Header and Payload sections expand vertically to fill the available page space
- Minimum vertical sizes are unchanged so still enable scrolling on short window heights
Behavior Before:
Behavior After:
- [ x ] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [ x ] Verified that the change work in …
> Allowing Vertical Stretch of JWT Header and Payload sections

- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/Formatter.cs
- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/TokenHelper.cs
- src/tests/DevToys.Tests/Providers/Tools/SqlFormatterTests.cs
Issue Number: #773
- The reserved keyword of "VALUES" will also be considered when omitting trimming of the end of new line spacing while formatting SQL.  The current implementation includes `LineComment`, `Operator`, and `OpenParen`.
> Fixing bug in sql formatter where values provided after reserved 'VALUES' keyword were not being indented properly

- src/dev/impl/DevToys/Helpers/SqlFormatter/Core/Tokenizer.cs
Issue Number: #816
I corrected wrong formatting, similar behavior appears when selecting TSQL, Standart Sql, Postgres, N1QL
Before correction:
Input:
<pre>
<code>
SELECT
U1.FULL_NAME || ' (' || U1.USER_NAME || ')' AS CREATED_BY,
U2.FULL_NAME || ' (' || U2.USER_NAME || ')' AS LAST_EDITED_BY
FROM SOMETABLE
</code>
</pre>
Output:
<pre>
<code>
SELECT
U1.FULL_NAME | | ' (' | | U1.USER_NAME | | ')' AS CREATED_BY,
U2.FULL_NAME | | ' (' | | U2.USER_NAME | | ')' AS LAST_EDITED_BY
FROM
SOMETABLE
</code>
</pre>
After correcting:
Input:
<pre>
<code>
SELECT
U1.FULL_NAME || ' (' || U1.USER_NAME || ')' AS CREATED_BY,
U2.FULL_NAME || ' (' || U2.USER_NAME || ')' AS LAST_EDITED_BY
FROM SOMETABLE
</code>
</pre>
Output:
<pre>
<code>
SELECT
U1.FULL_NAME || ' …
> Fixed sql formatting for logical operators

- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Strings/en-US/StringUtilities.resw
- src/dev/impl/DevToys/ViewModels/Tools/Text/StringUtilities/StringUtilitiesToolViewModel.cs
- src/dev/impl/DevToys/Views/Tools/Text/StringUtilities/StringUtilitiesToolPage.xaml
- src/tests/DevToys.Tests/Providers/Tools/StringUtilitiesTests.cs
Issue Number: #232
Add the following functions to the string utilities tool. These operate on lines of text.
- Alphabetize
- Reverse alphabetize
- Alphabetize by last word
- Reverse alphabetize by last word
- Reverse
- Randomize
https://github.com/veler/DevToys/assets/7417301/9e31476f-dd56-4e01-8edf-d6b150d4d3b1
All of the line splitting is done on CR (`\r`). I noticed that this is the line separator used for typed text and loaded files using any line endings (CR, LF,"or or CRLF). I don't really understand why, but it seems consistent.
For sorting by last word, I'm splitting on space and also comma (to accommodate CSV and last,first formatting).
It might be ever so slightly confusing that the "Original text" button is under the "Convert" …
> Add line sorting to string utils

- src/app/dev/DevToys.Blazor/Components/ContextMenu/ContextMenu.razor.cs
- src/app/dev/DevToys.Blazor/Core/Services/ContextMenuService.cs
- src/app/dev/DevToys.Blazor/Core/Services/IWindowService.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/App.xaml.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/Core/WindowService.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/MauiProgram.cs
- src/app/dev/platforms/desktop/DevToys.Windows/Core/WindowService.cs
- src/app/dev/platforms/desktop/DevToys.Windows/MainWindow.xaml
- src/app/dev/platforms/desktop/DevToys.Windows/MainWindow.xaml.cs
We added context menu support. However, the context menu would not close when :
- The window is resized.
- The window is moved.
- The window loses focus.
- The window is about to get closed.
We now close the context menu on all these events, on Windows and MacOS.
> [Dev/2.0] close context menu on window events

- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoder.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderControlViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtEncoderControlViewModel.cs
- src/tests/DevToys.Tests/Providers/Tools/JwtDecoderEncoderTests.cs
- src/tests/DevToys.Tests/Providers/Tools/JwtDecoderTests.cs
Unless I'm missing something obvious, it's currently impossible to validate tokens with a public key due to two issues:
- The token algorithm is never set, so the key-building code always tries the wrong algorithm.
- The public key text box is never displayed, because the visibility is only changed after a successful validation, which can't happen without the public key (chicken-and-egg).
(The unit tests have worked because they set the algorithm and public key explicitly.)
I also fixed a small issue related to **en**coding where the error banner would show when there wasn't an error and hide when there was!
**Before**: Don't even see the option for a public key. Obviously pasting it in the signature field doesn't work. …
> Fix JWT key validation

- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Models/JwtDecoderEncoder/DecoderParameters.cs
- src/dev/impl/DevToys/Strings/en-US/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoder.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderControlViewModel.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderEncoderSettings.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderEncoderViewModelBase.cs
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderControl.xaml
- src/tests/DevToys.Tests/Providers/Tools/JwtDecoderTests.cs
It is impossible to "validate" various parts of a JWT without providing the signature / signing key.
This PR separates signing key validation as a separate step from overall token validation. As a result, I can choose to validate only the expiration, for example, without providing a key, which is much more convenient.
https://github.com/veler/DevToys/assets/7417301/e3fd3a9d-a04f-4c53-ad62-4532e02853ec
If we were starting from scratch, I think it would make sense for the overall validation operation to be called something like `ValidateToken`, and then it could have an option like `ValidateSignature`. However, the latter term is already used for the whole operation (and refers to a persistent setting), so I didn't want to change that. …
> Allow token validation without signature

- src/dev/impl/DevToys/DevToys.csproj
- src/dev/impl/DevToys/LanguageManager.cs
- src/dev/impl/DevToys/Models/JwtDecoderEncoder/TokenResult.cs
- src/dev/impl/DevToys/Strings/en-US/Common.resw
- src/dev/impl/DevToys/Strings/en-US/JwtDecoderEncoder.resw
- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml
- src/dev/impl/DevToys/UI/Controls/CodeEditor.xaml.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtClaim.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoder.cs
- src/dev/impl/DevToys/ViewModels/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderControlViewModel.cs
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderControl.xaml
- src/dev/impl/DevToys/Views/Tools/EncodersDecoders/JwtDecoderEncoder/JwtDecoderControl.xaml.cs
Issue Numbers: #607 and #670
This PR adds the ability to show additional information about a decoded JWT. Key features are...
- Each top-level property of the JWT is shown in a table with the key in one column and the value in another.
- The values of date/time fields are shown in human-readable formats (instead of timestamp/long).
- Clicking the row for a given field will display an explanation about that field (if it is a known/documented JWT claim).
- There are descriptions for claims from [RFC 7519 Section 4.1](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1) and the [OpenID Connect Core Section 5.1, 2, 3.3.2.11, and 7.4](https://openid.net/specs/openid-connect-core-1_0.html) using the [IANA …
> Show additional JWT info

- src/dev/impl/DevToys/Strings/en-US/CRONParser.resw
The CronParser tool has the following label: 
"Choose whatever Cron expression should includes seconds in its definition"
Changed it to 
"Choose whether the Cron expression should include seconds in its definition"
- [] Did you verify that the change work in Release build configuration
- [] Did you verify that all unit tests pass
> Enhance label readability in Cron Parser

- src/app/dev/DevToys.Blazor/Pages/SubPages/ToolPage.razor
- src/app/dev/DevToys.Blazor/Pages/SubPages/ToolPage.razor.cs
- src/app/dev/DevToys.Core/Debugger/HotReloadEventArgs.cs
- src/app/dev/DevToys.Core/Debugger/HotReloadService.cs
DevToys 2.0 was supporting Hot Reload through a button added to the UI that forces the app to rebuild the view of a `IGuiTool`. This required the developer to explicitly click on this "Hot reload" button.
We now use `System.Reflection.Metadata.MetadataUpdateHandler` to get notified at runtime that Hot Reload occurred, and we reload the view of the active tool when it happens.
More info: https://learn.microsoft.com/en-us/visualstudio/debugger/hot-reload-metadataupdatehandler
https://github.com/veler/DevToys/assets/3747805/e8ab8016-65f4-4b58-8d1e-91d3c8fa7020
> Improved Hot Reload support

- src/app/dev/DevToys.Api/Core/IFileStorage.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIDropDownButton.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIDropDownMenuItem.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIElement.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIGridCell.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUINumberInput.cs
- src/app/dev/DevToys.Api/ViewModelBase.cs
- src/app/dev/DevToys.Blazor/Components/BasicInput/DropDownButton/DropDownButton.razor.cs
- src/app/dev/DevToys.Blazor/Components/Feedback/FontIcon/FontIcon.razor
- src/app/dev/DevToys.Blazor/Components/UIElements/UIDropDownButtonPresenter.razor
- src/app/dev/DevToys.Blazor/Components/UIElements/UIDropDownButtonPresenter.razor.cs
- src/app/dev/DevToys.Blazor/Components/UIElements/UIElementPresenter.razor
- src/app/dev/DevToys.Blazor/Components/UIElements/UITextInputWrapper.razor.cs
- src/app/dev/DevToys.Tools/Helpers/JsonTableHelper.cs
- src/app/dev/DevToys.Tools/Tools/Converters/JsonTable/JsonTableConverter.Designer.cs
- src/app/dev/DevToys.Tools/Tools/Converters/JsonTable/JsonTableConverter.resx
- src/app/dev/DevToys.Tools/Tools/Converters/JsonTable/JsonTableConverterGuiTool.cs
- src/app/dev/DevToys.Tools/Tools/Text/MarkdownPreview/MarkdownPreviewGuiTool.cs
We just added a JSON > Table converter tool to DevToys 2.0. See #1003.
The UI could be improved using a Drop Down Button, which isn't available in our API yet.
Issue Number: #1005
1. Added `IUIDropDownButton`.
2. Updated `JSON > Table` tool with a drop down button on top of the Data Grid that allows to copy or save the grid as CSV.
3. Did some refactoring
4. Added `StepChanged` event to `IUINumberInput` (seems like it got forgotten)
Before:
After:
> Added IUIDropDownButton and improve Json > Table UI

- src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/Monaco/TextModel.cs
- src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/MonacoEditor.razor.cs
- src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/MonacoEditorDiff.razor.cs
- src/app/dev/DevToys.Blazor/Core/Converters/PolymorphicConverter.cs
- src/app/dev/DevToys.Blazor/Core/Converters/PolymorphicConverterFactory.cs
- src/app/dev/DevToys.Blazor/Core/Extensions/JsonExtensions.cs
In preparation of @btiteux work on `JWT Encoder / Decoder`, I was curious to demonstrate how to use `Monaco Editor` API to show some text on a given span when the mouse pass the mouse hover it. Like this:
Unfortunately, I quickly faced a bug where the JSON we pass from .NET code to JavaScript code has some properties that aren't expected by Monaco.
To add a message on hover of a span in Monaco, we need to create an instance of [MarkdownString](https://github.com/veler/DevToys/blob/769a0e8fcbd91c85397d557c48f060bb17748fa7/src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/Monaco/MarkdownString.cs#L7-L18).
The minimum needed to make it work is to set a string to its `Value` property. However, that wasn't working.
The reason why is …
> Enabled Hover capability on Monaco Editor and fixed JSON serialization issue.

- src/app/dev/DevToys.Blazor/Pages/Index.razor.cs
- src/app/dev/DevToys.Business/ViewModels/MainWindowViewModel.cs
1. Go to Extension Manager
2. Click "Install". A dialog asking to click "I understand" opens.
3. Go in VS Code or web browser: Copy a Markdown code
4. Go back to DevToys.
DevToys will switch to the Markdown Preview tool because of Smart Detection. The dialog will still be opened but will be empty (no content inside). User is trapped. No way to close the dialog.
We do not run Smart Detection while a dialog is opened.
> Fixed bug: Smart detection when dialog opened

- src/app/dev/DevToys.Api/Settings/SettingDefinition.cs
- src/app/dev/DevToys.Core/Settings/PredefinedSettings.cs
- src/app/dev/DevToys.Core/Settings/SettingsProvider.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/AppDelegate.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/Core/WindowService.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/Views/MainWindow.cs
- src/app/dev/platforms/desktop/DevToys.Windows/MainWindow.xaml.cs
DevToys 2.0's window's size and position weren't saved and restore after closing/starting the app.
We now do it on Windows and MacOS.
We won't do it on Linux because GTK 4 doesn't have an API to move and resize a window (same reason why we don't support Picture-in-Picture)
> Window position and size is now saved and restore when reopening the app

- src/app/dev/DevToys.Core/FileHelper.cs
- src/app/dev/platforms/desktop/DevToys.CLI/Core/FileStorage/FileStorage.cs
- src/app/dev/platforms/desktop/DevToys.CLI/Strings/CliStrings/CliStrings.Designer.cs
- src/app/dev/platforms/desktop/DevToys.CLI/Strings/CliStrings/CliStrings.resx
`IFileStorage` in DevToys.CLI was missing some functionalities.
Completed missing parts of IFileStroage in DevToys CLI
Performed some manual tests.
> Completed missing parts of IFileStorage in DevToys CLI

- src/app/dev/DevToys.Tools/Helpers/StringHelper.cs
- src/app/dev/DevToys.Tools/Tools/Text/AnalyzerAndUtilities/AnalyzerAndUtilities.Designer.cs
- src/app/dev/DevToys.Tools/Tools/Text/AnalyzerAndUtilities/AnalyzerAndUtilities.resx
- src/app/dev/DevToys.Tools/Tools/Text/AnalyzerAndUtilities/AnalyzerAndUtilitiesCommandLineTool.cs
- src/app/dev/DevToys.Tools/Tools/Text/AnalyzerAndUtilities/AnalyzerAndUtilitiesGuiTool.cs
- src/app/tests/DevToys.UnitTests/Tools/Helpers/StringHelperTests.cs
Implemented the case converter described in the issue below:
Issue Number: #1055 
- New converter button 'raNdoM cASe' added to Text Analyzer and Utilities
- Text character cases are randomly changed in the string when the button is clicked
> Random case/spongetext case converter implementation

- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIMultiLineTextInput.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/UIHighlightedTextSpan.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/UIHoverTooltip.cs
- src/app/dev/DevToys.Blazor/BuiltInTools/Settings/SettingsGuiTool.cs
- src/app/dev/DevToys.Blazor/Components/UIElements/UIMultiLineTextInputPresenter.razor.cs
1. The method to create `IUIMultiLineTextInput` is inconsistent with `IUISingleLineTextInput`.
2. The `UIHoverTooltip` is inconsistent with `UIHighlightedTextSpan`, which they do similar things (add decoration to text)
3. There is a bug: when setting Highlights, it removed Tooltip and vice versa.
1. Made the API more consistent (This causes a breaking change. Will need to update NuGet package and `DevToys.Tools`)
2. Fixed the bug in `MultiLineTextInputPresenter`
> Fixed inconcistency and bug in IUIMultilineTextInput

- src/app/dev/DevToys.Api/Settings/SettingDefinition.cs
Issue Number: #1139
SettingsDefinition now use the assembly name, namespace and class of the caller in order to reduce chances of colliding setting name.
> Made settings name less prone to collision

- .vscode/launch.json
- CONTRIBUTING.md
The paths for MacOS build on `launch.json` are obsolete and need to be fixed to work properly.
Issue Number: #1126 
- Fixes the paths on the launch tasks "DevToys MacOS arm64" and "DevToys MacOS x64"
> Minor updates on MacOS paths and documentation

- src/app/dev/DevToys.Business/ViewModels/MainWindowViewModel.cs
- src/app/dev/DevToys.Core/Tools/GuiToolInstance.cs
- src/app/dev/DevToys.Core/Tools/GuiToolProvider.cs
- src/app/dev/DevToys.Core/Tools/SmartDetectionService.cs
- src/app/dev/platforms/desktop/DevToys.CLI/CommandToICommandLineToolMap.cs
- src/app/dev/platforms/desktop/DevToys.CLI/OptionToICommandLineToolMap.cs
- src/app/dev/platforms/desktop/DevToys.CLI/Program.cs
Issue Number: #1160
We now safely handle extensions that aren't well configured, preventing a total crash of DevToys, logging failures, and when possible, displaying explicitly what's wrong.
> Safely handle misconfigured extensions

- src/app/dev/platforms/desktop/DevToys.Linux/Core/Clipboard.cs
GirCore provides a new async method to read text from a Gdk.Clipboard.
-
-
-
> Linux.Clipboard: Use a new method to read text

- src/app/dev/DevToys.Core/AppHelper.cs
- src/app/tests/DevToys.UnitTests/Core/AppHelperTests.cs
DevToys current version is `v2.0-preview.1`. We recently dropped the Revision number (4th digit) because the MS Store and Homebrew only accept 3 digits version number. This regressed the update detection.
GitHub release is "v2.0.1.0", which is parsed as a `System.Version(2, 0, 1, 0)`.
DevToys running version is "v2.0-preview.1", which is parsed as `System.Version(2, 0, 1, -1)`.
Because of this, DevToys finds that there's a newer version on GitHub, which is wrong.
We now only check the first 3 digits (Major, Minor, Build).
> Fixed an issue where the app wrongly detect an update

- src/app/dev/platforms/desktop/DevToys.MacOS/Core/Clipboard.cs
Issue Number: #1203 
It seems like in **some** cases, the clipboard API isn't invoked from the Ui thread, causing an internal error because it needs it to access the clipboard. It mainly impacts text box.
Switch to the UI thread before accessing the clipboard.
> Fixed failure to access clipboard in MacOS

- src/app/dev/platforms/desktop/DevToys.Windows/Controls/MicaWindowWithOverlay.xaml.cs
Issue Number: #1219
https://github.com/DevToys-app/DevToys/assets/3747805/f080b117-35a9-4432-954b-75104db66de9
https://github.com/DevToys-app/DevToys/assets/3747805/9444e6f0-6e99-4d53-9043-d5aca5876c76
> Fix bug where we can't restore the window when maximized on Windows 10/11

- src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/MonacoEditor.razor
- src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/MonacoEditor.razor.cs
- src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/MonacoEditorDiff.razor
- src/app/dev/DevToys.Blazor/Components/Text/MonacoEditor/MonacoEditorDiff.razor.cs
Issue Number: #1243
From what I've seen personally and from what customers share on GitHub and social network, Monaco tend to load instantly, and our loading progress indication is more bothering than helpful. Let's remove it completely.
- [] Did you check for accessibility? On Windows, you can use Accessibility Insights for this.
> Remove loading indication for Monaco

- src/app/dev/platforms/desktop/DevToys.MacOS/Controls/BlazorWebView/BlazorWKWebView.cs
- src/app/dev/platforms/desktop/DevToys.MacOS/Controls/BlazorWebView/BlazorWebViewManager.cs
Issue Number: #1279
`BlazorWebView` now navigates to `app://localhost` instead of `app://0.0.0.0` on MacOS 15.0
> [MacOS] Fixed an issue where the app is completely blank on MacOS 15 Beta

- src/app/dev/DevToys.Blazor/BuiltInTools/ExtensionsManager/ExtensionInstallationManager.cs
- src/app/dev/DevToys.Blazor/BuiltInTools/ExtensionsManager/ExtensionsManagerGuiTool.cs
- src/app/dev/DevToys.Blazor/BuiltInTools/SupportDevelopment/SupportDevelopmentGuidTools.cs
- src/app/dev/DevToys.Blazor/Pages/Index.razor
- src/app/dev/DevToys.Blazor/Pages/Index.razor.cs
- src/app/dev/DevToys.Business/ViewModels/MainWindowViewModel.cs
- src/app/dev/DevToys.Localization/Strings/MainWindow/MainWindow.Designer.cs
- src/app/dev/DevToys.Localization/Strings/MainWindow/MainWindow.resx
When `Check for update on start` option is ON, DevToys will check for update of extension and notify the user about it in the UI. It won't install the update automatically (maybe something to add in the future)
> Added check for update for extensions

- src/app/dev/DevToys.Core/Tools/GuiToolProvider.cs
Some extensions use the same name in `IResourceAssemblyIdentifier`, and it causes some conflicts internally.
We now test the resource manager and try with a different assembly if it doesn't work. I also updated the documentation (in Documentation repository) to explain that the name should be unique.
> Added conflict internal name resolution for resource assembly identifier.

- .github/advanced-issue-labeler.yml
- .github/workflows/issue_labeler.yml
Add a workflow that automatically assigns labels to issues corresponding to the app type and platform.
This makes it easier to manage issues. Specifically, it makes it easier to identify and narrow down the environment in which bugs are identified from the issue list.
- Assign the appropriate label to the issue
- The workflow uses [advanced-issue-labeler](https://github.com/marketplace/actions/advanced-issue-labeler) for labeling.
- If you add a new issues template, simply edit issue_labeler.yml and if you add a new dropdown or label, edit advanced-issue-labeler.yml
Examples of Operation
> Add workflow to label issues.

- src/app/dev/DevToys.Core/Tools/GuiToolProvider.cs
- src/app/tests/DevToys.UnitTests/Core/Tools/GuiToolProviderTests.cs
Issue Number: fix #1401
Changed the cherry picking logic in search algorithm to consider all items that are down to 45% of the highest match weight.
> Improved search accuracy

- src/app/dev/DevToys.Core/Mef/AssemblyIsolation.cs
- src/app/dev/DevToys.Core/Mef/RecursiveDirectoryCatalog.cs
Issue Number: fix #1430
Added a `AssemblyLoadContext` per extension discovered in DevToys, which allows each extension to load every assemblies it needs in an isolated manner. This allows .NET to load and use multiple versions of an assembly at the same time.
**Note:** This feature is NOT supported by Android, iOS and WebAssembly. But we don't care since we don't target them.
You can test the change by building and installing the 2 extensions in this ZIP: 
[ExtensionTest.zip](https://github.com/user-attachments/files/17534932/ExtensionTest.zip)
> Added support of per-extension assembly isolation

- src/app/dev/DevToys.Api/Tool/GUI/Components/IUICard.cs
- src/app/tests/DevToys.UnitTests/Tool/GUI/Components/UIElementWithChildrenTests.cs
Fixes: #1406 
- `GetChildElementById` now also iterates over `UIElement` inside `UICard`.
Added basic unit tests for `GetChildElementById`.
>  Fix GetChildElementById no access to elements inside Card

- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIButton.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIDropDownButton.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIDropDownMenuItem.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIIcon.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIUtf32GlyphProvider.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIUtf32Icon.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIUtf32IconButton.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIUtf32IconDropDownButton.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIUtf32IconDropDownMenuItem.cs
- src/app/dev/DevToys.Api/Tool/GUI/Components/IUIUtf32IconProvider.cs
- src/app/dev/DevToys.Blazor/Components/BasicInput/DropDownButton/DropDownListItem.cs
- src/app/dev/DevToys.Blazor/Components/Feedback/FontIcon/FontIcon.razor
- src/app/dev/DevToys.Blazor/Components/Feedback/FontIcon/FontIcon.razor.cs
- src/app/dev/DevToys.Blazor/Components/UIElements/UIButtonPresenter.razor
- src/app/dev/DevToys.Blazor/Components/UIElements/UIDropDownButtonPresenter.razor
- src/app/dev/DevToys.Blazor/Components/UIElements/UIDropDownButtonPresenter.razor.cs
- src/app/dev/DevToys.Blazor/Components/UIElements/UIIconPresenter.razor
Added components that extend the size of the icon Glyph to 32-bit.
See discussions #1399
- Added classes for Utf32Icon derived from the following components:
- UIIcon
- UIButton
- UIDropDownButton
- UIDropDownMenuItem
- Introduced helper methods in DevToys.Api.GUI for creating instances of Utf32Icon components. These methods take the font name and the int type Glyph code as arguments to create instances of the Utf32Icon version.
Example Usage
```cs
IUIUtf32Icon icon32 = Icon("FluentSystemIcons", 983184);
IUIUtf32IconButton button32 = Button("FluentSystemIcons", 983184, "Button");
IUIUtf32IconDropDownButton ddButton32 = DropDownButton("FluentSystemIcons", 983184, "DDButton");
IUIUtf32IconDropDownMenuItem ddMenuItem = …
```
> Add support for UTF-32 glyphs in icon components

- src/app/dev/platforms/desktop/DevToys.Windows/Controls/OverlayWindow.xaml.cs
- src/app/dev/platforms/desktop/DevToys.Windows/Native/HwndSourceMessages.cs
- src/app/dev/platforms/desktop/DevToys.Windows/Native/NativeMethods.cs
Issue Number: fix #1455
Use Win32 API to hide the window from Alt+Tab
> Fixed issue where a blank window appears in Alt+Tab in Windows
